bin: massive cleanup and unification

diff --git a/bin/64bits b/bin/64bits
--- a/bin/64bits
+++ b/bin/64bits
@@ -9,7 +9,10 @@
 # under certain conditions.
 #
 
-[ ! -x `which file` ] && echo "E: file: Command not found" >&2 && exit 1
+[ -z "`which file`" ] && echo "64bits: command 'file' not found" >&2 && exit 1
 
 echo "System: "$(uname -o)" "$(file -b `which file` | awk '{print $2}')
 echo "Supports 64bits: "$(cat /proc/cpuinfo | grep flags | grep lm > /dev/null && echo "Yes" || echo "No")
+#echo "libc: v"$(dpkg -l | egrep '^ii  libc6 ' | awk '{print $3}')
+
+# EOF
diff --git a/bin/big b/bin/big
--- a/bin/big
+++ b/bin/big
@@ -10,17 +10,19 @@
 #
 
 if [ $# -ne 2 ] ; then
-    echo "Usage: `basename "$0"` <DIR> <SIZE>" >&2
+    echo "Usage: big <dir> <size>" >&2
     echo "       SIZE is in bytes but can be 512M and so on" >&2
     exit 1
 fi
 
 DIR=$(readlink -f "$1")
 SIZE=$(echo "$2" | tr "[a-z]" "[A-Z]" | egrep "^[0-9]+[MGT]?$")
-[ ! -e "$DIR" ] && echo "E: $DIR: No such file or directory" >&2 && exit 1
-[ ! -d "$DIR" ] && echo "E: $DIR: Not a directory" >&2 && exit 1
-[ ! -r "$DIR" ] && echo "E: $DIR: Permission denied" >&2 && exit 1
-[ "_$SIZE" = "_" ] && echo "E: Invalid size" >&2 && exit 1
+[ ! -e "$DIR" ] && echo "big: $DIR: no such file or directory" >&2 && exit 1
+[ ! -d "$DIR" ] && echo "big: $DIR: not a directory" >&2 && exit 1
+[ ! -r "$DIR" ] && echo "big: $DIR: permission denied" >&2 && exit 1
+[ -z "$SIZE" ] && echo "big: invalid size" >&2 && exit 1
 
 echo " * Searching in $DIR for files bigger than ${SIZE}B..."
 find "$DIR" -type f -size +$SIZE -exec ls -lh {} \; 2>/dev/null | sed -r 's/ +/ /g' | cut -d' ' -f5,9-
+
+# EOF
diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -1,19 +1,8 @@
 #!/bin/bash
 #
 # extract -- one script to extract them all
-# Copyright (C) 2008-2010  Alan "Shtark" SCHNEIDER
+# Copyright (C) 2008-2012  Alan "Shtark" SCHNEIDER
 #                          <shk.schneider[at]gmail.com>
-# ChangeLog:
-#	v1.3	2010	added generic decompression if everything else failed using p7zip and tar
-#			added generic decompression: *.tar.* *.t*
-#			added support for lzma archives
-#	v1.2	2010	improved commands
-#       v1.1    2010	support for spaces in names
-#	v1.0	2010	rewritten
-#			now supports .tar.bz2 .tar.gz .tar.xz .bz2 .rar .gz .tar
-#			.tbz2 .tgz .zip .Z .7z .xz .exe .rpm .deb .iso .ace
-#	v0.2	2009	extended version with .rar .gz .tgz and better code
-#	v0.1	2008	basic version for .tar.gz .zip .tar.bz2
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
@@ -22,7 +11,7 @@
 
 function cmd() {
     for BIN in "$1" ; do
-	[ -n `which $BIN` ] && echo "E: $BIN: Command not found" >&2 && return 1
+	[ -n "`which $BIN`" ] && echo "extract: command '$BIN' not found" >&2 && return 1
     done
     return 0
 }
@@ -68,12 +57,12 @@ function extract() {
     esac
 }
 
-[ $# -eq 0 ] && echo "Usage: `basename "$0"` <FILE> [...]" >&2 && exit 1
+[ $# -eq 0 ] && echo "Usage: extract <file [...]>" >&2 && exit 1
 
 for FILE in "$@" ; do
-    [ ! -e "$FILE" ] && echo "E: $FILE: No such file or directory" >&2 && exit 1
-    [ -d "$FILE" ] && echo "E: $FILE: Is a directory" >&2 && exit 1
-    [ ! -r "$FILE" ] && echo "E: $FILE: Permission denied" >&2 && exit 1
+    [ ! -e "$FILE" ] && echo "extract: $FILE: no such file or directory" >&2 && exit 1
+    [ -d "$FILE" ] && echo "extract: $FILE: is a directory" >&2 && exit 1
+    [ ! -r "$FILE" ] && echo "extract: $FILE: permission denied" >&2 && exit 1
     FILE=$(readlink -f "$FILE")
     NAME=$(basename "$FILE" | sed -r 's/(\.[a-zZ2]{2,3})?\.[a-zZ2]{1,4}$//')
     if [ -d "$NAME" ] ; then
@@ -86,3 +75,5 @@ for FILE in "$@" ; do
     mkdir "$NAME" && cd "$NAME"
     extract
 done
+
+# EOF
diff --git a/bin/git-tarball b/bin/git-tarball
--- a/bin/git-tarball
+++ b/bin/git-tarball
@@ -9,10 +9,10 @@
 # under certain conditions.
 #
 
-[ -z `which git` ] && echo "E: git: Command not found" >&2 && exit 1
+[ -z "`which git`" ] && echo "git-tarball: command 'git' not found" >&2 && exit 1
 
 function usage() {
-    echo "Usage: git-tarball {tag|commit}" >&2
+    echo "Usage: git-tarball <tag|commit>" >&2
     exit 1
 }
 
diff --git a/bin/gnome-menu b/bin/gnome-menu
--- a/bin/gnome-menu
+++ b/bin/gnome-menu
@@ -9,9 +9,11 @@
 # under certain conditions.
 #
 
-[ ! -x `which gconftool` ] && echo "E: gconftool: Command not found" >&2 && exit 1
+[ -z "`which gconftool`" ] && echo "gnome-menu: command 'gconftool' not found" >&2 && exit 1
 
 echo " * button_layout = menu:minimize,maximize,close"
 gconftool-2 --set /apps/metacity/general/button_layout --type string "menu:minimize,maximize,close"
 echo " * menu_have_icons = true"
 gconftool-2 --set /desktop/gnome/interface/menus_have_icons --type boolean "true"
+
+# EOF
diff --git a/bin/mkv2avi b/bin/mkv2avi
--- a/bin/mkv2avi
+++ b/bin/mkv2avi
@@ -9,19 +9,19 @@
 # under certain conditions.
 #
 
-[ ! -x `which mencoder` ] && echo "E: mencoder: Command not found" >&2 && exit 1
-[ ! -x `which lame` ] && echo "E: lame: Command not found" >&2 && exit 1
-[ ! -x `which ffmpeg` ] && echo "E: ffmpeg: Command not found" >&2 && exit 1
-[ ! -x `which du` ] && echo "E: du: Command not found" >&2 && exit 1
+[ -z "`which mencoder`" ] && echo "mkv2avi: command 'mencoder' not found" >&2 && exit 1
+[ -z "`which lame`" ] && echo "mkv2avi: command 'lame' not found" >&2 && exit 1
+[ -z "`which ffmpeg`" ] && echo "mkv2avi: command 'ffmpeg' not found" >&2 && exit 1
+[ -z "`which du`" ] && echo "mkv2avi: command 'du' not found" >&2 && exit 1
 
-[ $# -eq 0 ] && echo "Usage: `basename "$0"` <FILE> [...]" >&2 && exit 1
+[ $# -eq 0 ] && echo "Usage: mkv2avi <file [...]>" >&2 && exit 1
 
 SIZE=0
 for FILE in "$@" ; do
     FILE=$(readlink -f "$FILE")
-    [ ! -e "$FILE" ] && echo "E: $FILE: No such file or directory" >&2 && exit 1
-    [ -d "$FILE" ] && echo "E: $FILE: Is a directory" >&2 && exit 1
-    [ ! -r "$FILE" ] && echo "E: $FILE: Permission denied" >&2 && exit 1
+    [ ! -e "$FILE" ] && echo "mkv2avi: $FILE: no such file or directory" >&2 && exit 1
+    [ -d "$FILE" ] && echo "mkv2avi: $FILE: is a directory" >&2 && exit 1
+    [ ! -r "$FILE" ] && echo "mkv2avi: $FILE: permission denied" >&2 && exit 1
     INPUT_SIZE=$(du -s "$FILE" | tr "\t" " " | cut -d' ' -f1)
     SIZE=$(($SIZE + $INPUT_SIZE))
 done
@@ -73,3 +73,5 @@ if [ $F -ne $I ] ; then
 	echo "$I files deleted"
     fi
 fi
+
+# EOF
diff --git a/bin/netcraft b/bin/netcraft
--- a/bin/netcraft
+++ b/bin/netcraft
@@ -9,11 +9,11 @@
 # under certain conditions.
 #
 
-[ -z "`cat /proc/net/arp | egrep '^[0-9]'`" ] && echo "E: `basename "$0"`: No network connection" >&2 && exit 1
-[ ! -x `which curl` ] && echo "E: curl: Command not found" && exit 1
+[ -z "`cat /proc/net/arp | egrep '^[0-9]'`" ] && echo "netcraft: no network connection" >&2 && exit 1
+[ -z "`which curl`" ] && echo "netcraft: command 'curl' not found" && exit 1
 
 if [ $# -eq 0 ] ; then
-    echo "Usage: `basename "$0"` <host> [...]" >&2
+    echo "Usage: netcraft <host [...]>" >&2
     echo "       host must be HTTP or HTTPS" >&2
     exit 1
 fi
@@ -45,8 +45,8 @@ for ARGV in $@ ; do
 	    continue
 	    ;;
 	*)
-	    if [ "_`echo "$ARGV" | egrep '^[a-z]*://'`" != "_" ] ; then
-		echo "E: Unsupported protocol: \`"$(echo "$ARGV" | cut -d':' -f1)"'" >&2
+	    if [ -n "`echo "$ARGV" | egrep '^[a-z]*://'`" ] ; then
+		echo "netcraft: unsupported protocol '"$(echo "$ARGV" | cut -d':' -f1)"'" >&2
 		continue
 	    fi
 	    get_server "http://$ARGV"
@@ -54,3 +54,5 @@ for ARGV in $@ ; do
 	    ;;
     esac
 done
+
+# EOF
diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -14,11 +14,13 @@ CPUINFO=$(cat /proc/cpuinfo | grep flags | grep ' lm ')
 [ -z "$CPUINFO" ] && CPU="x86" || CPU="x64"
 KERNEL=$(uname -sr | cut -d'-' -f1)
 
-if [ ! -x `which lsb_release` ] ; then
-    echo "W: lsb_release: Command not found" >&2
+if [ -z "`which lsb_release`" ] ; then
+    echo "release: command 'lsb_release' not found" >&2
     echo "GNU/Linux $CPU [$LANG] with $KERNEL"
 else
     DISTRIB=$(lsb_release -i | awk '{printf $NF}')
     VERSION=$(lsb_release -sr)" \"$(exec lsb_release -sc | sed 's/^[a-z]/\U&/')"\"
     echo "GNU/Linux $DISTRIB $VERSION $CPU [$LANG] with $KERNEL"
 fi
+
+# EOF
diff --git a/bin/sdebpkg b/bin/sdebpkg
--- a/bin/sdebpkg
+++ b/bin/sdebpkg
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
 # sdebpkg -- simple deb packager from scratch
-# Copyright (C) 2011  Alan "Shtark" SCHNEIDER
-#                     <shk.schneider[at]gmail.com>
+# Copyright (C) 2011-2012  Alan "Shtark" SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
@@ -15,29 +15,27 @@
 # Please read:	<http://www.debian.org/doc/debian-policy/>
 #
 
-# v3.18
-
 COPYRIGHTS=$(find /usr/share/debhelper/dh_make/licenses -maxdepth 1 -type f | rev | cut -d'/' -f1 | rev | tr "\n" " ")
 ARCHS=$(dpkg-architecture -L | grep -v '-' | tr "\n" " ")"all"
 function usage() {
-    echo "Usage: `basename "$0"` [OPTIONS] <DIR>" >&2
+    echo "Usage: sdebpkg [options] <dir>" >&2
     echo "       prepare:" >&2
-    echo "       {-c|--copyright}              license for debian/control [be careful]" >&2
-    echo "           --list-copyrights" >&2
-    echo "       {-r|--reset}                  removes debian directory [be careful]" >&2
-    echo "       {-x|--extras}                 keep examples files form dh_make" >&2
+    echo "         {-c|--copyright}              license for debian/control [be careful]" >&2
+    echo "             --list-copyrights" >&2
+    echo "         {-r|--reset}                  removes debian directory [be careful]" >&2
+    echo "         {-x|--extras}                 keep examples files form dh_make" >&2
     echo "       build:" >&2
-    echo "       {-v|--verify}                 check debian policy" >&2
-    echo "       {-t|--tarball}                 keep .tar.gz" >&2
-    echo "       {-k|--keep-all}               keep everything (implies --tar-gz)" >&2
-    echo "       {-q|--quiet}                  less verbose packaging [be careful]" >&2
+    echo "         {-v|--verify}                 check debian policy" >&2
+    echo "         {-t|--tarball}                 keep .tar.gz" >&2
+    echo "         {-k|--keep-all}               keep everything (implies --tar-gz)" >&2
+    echo "         {-q|--quiet}                  less verbose packaging [be careful]" >&2
     echo "       any:" >&2
-    echo "       {-s|--summarize}              break after summary" >&2
-    echo "       {-a|--architecture} <ARCH>    target architecture" >&2
-    echo "           --list-architectures" >&2
-    echo "       {-i|--interactive}            prompt the user on each step and upon errors" >&2
-    echo "       {-f|--force}                  never get interactive even upon errors" >&2
-    echo "       {--help|--version|--author}" >&2
+    echo "         {-s|--summarize}              break after summary" >&2
+    echo "         {-a|--architecture} <ARCH>    target architecture" >&2
+    echo "             --list-architectures" >&2
+    echo "         {-i|--interactive}            prompt the user on each step and upon errors" >&2
+    echo "         {-f|--force}                  never get interactive even upon errors" >&2
+    echo "         {--help|--version|--author}" >&2
 }
 
 function pause() {
@@ -83,7 +81,7 @@ if [ -f ~/.sdebpkg ] ; then
 		"Architecture")	DEBARCH="$VALUE" ;;
 		"Priority")	DEBPRIORITY="$VALUE" ;;
 		"Section")	DEBSECTION="$VALUE" ;;
-		*)		echo "E: ~/.sdebpkg l.$L: Unknown var \`$VAR'" >&2 && E=1 ;;
+		*)		echo "E: ~/.sdebpkg l.$L: Unknown var '$VAR'" >&2 && E=1 ;;
 	    esac
 	    fi
 	    L=$(($L + 1))
@@ -165,10 +163,10 @@ DIRDIR=$(dirname "$DIR")
 if [ -f "$DIR/Makefile" ] ; then
     MAKEFILE=1
     E=0
-    [ -z "`egrep '^all:' "$DIR/Makefile"`" ] && E=1 && echo "E: $DIR/Makefile: No target \`all'" >&2 && exit 1
-    [ -z "`egrep '^install:' "$DIR/Makefile"`" ] && E=1 && echo "E: $DIR/Makefile: No target \`install'" >&2
-    [ -z "`egrep '^clean:' "$DIR/Makefile"`" ] && E=1 && echo "W: $DIR/Makefile: No target \`clean'" >&2
-    [ -z "`egrep '^distclean:' "$DIR/Makefile"`" ] && E=1 && echo "W: $DIR/Makefile: No target \`distclean'" >&2
+    [ -z "`egrep '^all:' "$DIR/Makefile"`" ] && E=1 && echo "E: $DIR/Makefile: No target 'all'" >&2 && exit 1
+    [ -z "`egrep '^install:' "$DIR/Makefile"`" ] && E=1 && echo "E: $DIR/Makefile: No target 'install'" >&2
+    [ -z "`egrep '^clean:' "$DIR/Makefile"`" ] && E=1 && echo "W: $DIR/Makefile: No target 'clean'" >&2
+    [ -z "`egrep '^distclean:' "$DIR/Makefile"`" ] && E=1 && echo "W: $DIR/Makefile: No target 'distclean'" >&2
     [ $E -ne 0 ] && pause 0
 else
     MAKEFILE=0
diff --git a/bin/supercopier b/bin/supercopier
--- a/bin/supercopier
+++ b/bin/supercopier
@@ -3,28 +3,22 @@
 # supercopier -- cp with progress bar (with pv)
 # Copyright (C) 2010-211  Alan "Shtark" SCHNEIDER
 #                         <shk.schneider[at]gmail.com>
-# ChangeLog:
-#	v0.4	2011	improved checks and script
-#	v0.3	2010	added support for directories and shell globings
-#                       released on <http://blog.shk-desktop.com>
-#       v0.2    2010    support for spaces in names
-#	v0.1	2010	support for single file
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
 # under certain conditions.
 #
 
-[ ! -x `which pv` ] && echo "E: pv: Command not found" >&2 && exit 1
+[ -z "`which pv`" ] && echo "supercopier: command 'pv' not found" >&2 && exit 1
 
-[ $# -lt 2 ] && echo "Usage: `basename "$0"` <source [...]> <destination>" >&2 && exit 1
+[ $# -lt 2 ] && echo "Usage: supercopier <source [...]> <destination>" >&2 && exit 1
 
 function supercopier() {
     # 1: source
     # 2: destination
-    [ ! -e "$1" ] && echo "E: $1: No such file or directory." >&2 && exit 1
-    [ ! -r "$1" ] && echo "E: $1: Premission denied." >&2 && exit 1
-    [ "$1" = "$2" ] && echo "E: Input file is output file." >&2 && exit 1
+    [ ! -e "$1" ] && echo "supercopier: $1: no such file or directory" >&2 && exit 1
+    [ ! -r "$1" ] && echo "supercopier: $1: premission denied" >&2 && exit 1
+    [ "$1" = "$2" ] && echo "supercopier: input file is output file" >&2 && exit 1
     [ -d "$S1" -a ! -d "$2" ] && mkdir -p "$2"
     OFFSET=$(echo "`tput cols` - `echo "$1$2 "| wc -c` - 6" | bc -q)
     printf " * %s -> %s %${OFFSET}s\n" "$1" "$2" $(du -sh "$SOURCE" 2>/dev/null | awk '{print $1}')
@@ -34,10 +28,10 @@ function supercopier() {
 	if [ -d "$SOURCE" ] ; then
 	    [ ! -d "$DESTINATION" ] && mkdir -p "$DESTINATION"
 	elif [ -d "$DESTINATION" ] ; then
-	    echo "E: $DESTINATION: Is a directory" >&2 && sleep 1
+	    echo "supercopier: $DESTINATION: is a directory" >&2 && sleep 1
 	else
 	    pv -pert "$SOURCE" > "$DESTINATION"
-	    [ $? -ne 0 ] && echo "E: pv seems to have failed ($?)" >&2 && sleep 1
+	    [ $? -ne 0 ] && echo "supercopier: pv seems to have failed ($?)" >&2 && sleep 1
 	fi
     done
 }
@@ -61,3 +55,5 @@ else
 	[ $I -eq $# ] && break
     done
 fi
+
+# EOF
