2016 freshness

diff --git a/bin/ascii-art b/bin/ascii-art
--- a/bin/ascii-art
+++ b/bin/ascii-art
@@ -1,8 +1,8 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # ascii-art -- ascii art out of simple strings
-# Copyright (C) 2013  Alan SCHNEIDER
-#                     <shk.schneider[at]gmail.com>
+# Copyright (C) 2013-2016  Alan SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # From <http://www.network-science.de/ascii/>
 #
@@ -11,25 +11,27 @@
 # under certain conditions.
 #
 
-[ ! -x "$(which curl)" ] && echo "E: curl: command not found" >&2 && exit 1
+command -v curl >/dev/null 2>&1 || { echo "E: curl: command not found" >&2 ; exit 1 ; }
 
-chars='[a-zA-Z0-9\-]'
-
+chars='[a-zA-Z0-9\-]' # TODO urlencode?
 if [ $# -gt 0 ] ; then
     for argv in $@ ; do
-        # Allowed are a-z,A-Z,ä,ö,ü,å,0-9,_,+,-,blank,!,?,@,#,:,comma and dot.
+        # Allowed are a-z,A-Z,,0-9,_,+,-,blank,!,?,@,#,:,comma and dot.
         if [ -n "$(echo "$argv" | egrep "^${chars}+$")" ] ; then
             get="TEXT=${argv}&x=32&y=14&FONT=graffiti&RICH=no&FORM=left&STRE=no&WIDT=80"
-            curl --silent "http://www.network-science.de/ascii/ascii.php?${get}" | \
-                sed -n '35,39p' | \
-                sed 's/&lt;/>/g' | \
-                sed 's/&gt;/</g'
+            curl --silent "http://www.network-science.de/ascii/ascii.php?${get}" \
+                | sed -n '34,39p' \
+                | sed -r 's;^.+<[a-zA-Z]+>;;g' \
+                | sed 's/&lt;/>/g' \
+                | sed 's/&gt;/</g'
         else
-            echo "E: $argv: allowed characters are: ${chars}" >&2 && continue
+            echo "E: $argv: forbidden characters" >&2 && continue
         fi
     done
 else
     echo "Usage: $0 <text ...>" >&2 && exit 1
 fi
+
+exit 0
 
 # EOF
diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -1,7 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # extract -- one script to extract them all
-# Copyright (C) 2008-2012  Alan SCHNEIDER
+# Copyright (C) 2008-2016  Alan SCHNEIDER
 #                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
@@ -11,13 +11,13 @@
 
 function cmd() {
     for bin in "$1" ; do
-	[ -n "`which $bin`" ] && echo "extract: command '$bin' not found" >&2 && return 1
+        command -v "$bin" >/dev/null 2>&1 || { echo "E: $bin: command not found" >&2 ; return 1 ; }
     done
     return 0
 }
 
 function extract() {
-    echo " * Extracting `basename $file` to `pwd`..."
+    echo " * Extracting $(basename -- $file) to $(pwd)..."
     case "$file" in
 	*.tar)			cmd "tar" && tar xvf "$file" ;;
 	*.tar.bz2|*.tbz2)	cmd "tar" && tar xvjf "$file" ;;
@@ -63,10 +63,10 @@ for file in "$@" ; do
     [ ! -e "$file" ] && echo "extract: $file: no such file or directory" >&2 && exit 1
     [ -d "$file" ] && echo "extract: $file: is a directory" >&2 && exit 1
     [ ! -r "$file" ] && echo "extract: $file: permission denied" >&2 && exit 1
-    file=$(readlink -f "$file")
-    name=$(basename "$file" | sed -r 's/(\.[a-zZ2]{2,3})?\.[a-zZ2]{1,4}$//')
+    file=$(readlink -f -- "$file")
+    name=$(basename -- "$file" | sed -r 's/(\.[a-zZ2]{2,3})?\.[a-zZ2]{1,4}$//')
     if [ -d "$name" ] ; then
-	echo -n "   Directory \`$name' exists. Overwite [Y/n]? "
+	echo -n "   Directory '$name' exists. Overwite [Y/n]? "
 	read rep
 	[ "_$rep" = "_n" ] && continue
 	rm -rf "$name"
@@ -75,5 +75,7 @@ for file in "$@" ; do
     mkdir "$name" && cd "$name"
     extract
 done
+
+exit 0
 
 # EOF
diff --git a/bin/imgsz b/bin/imgsz
--- a/bin/imgsz
+++ b/bin/imgsz
@@ -1,24 +1,24 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # imgsz -- get image sizes and dpi
-# Copyright (C) 2012  Alan SCHNEIDER
-#                     <shk.schneider[at]gmail.com>
+# Copyright (C) 2012-2016  Alan SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
 # under certain conditions.
 #
 
-[ $# -eq 0 ] && echo "Usage: imgsz <img[ ...]>" >&2 && exit 1
+command -v sips >/dev/null 2>&1 || { echo "E: sips: command not found" >&2 ; exit 1 ; }
 
-[ ! -x "$(which sips)" ] && echo "E: sips: command not found" >&2 && exit 1
+[ $# -eq 0 ] && echo "Usage: imgsz <img[ ...]>" >&2 && exit 1
 
 for file in $@ ; do
     if [ ! -f "$file" ] ; then
-	echo "E: $file is not a file" >&2
+	echo "E: $file: not a file" >&2
 	continue
     elif [ ! -r "$file" ] ; then
-	echo "E: $file is not readable" >&2
+	echo "E: $file: not readable" >&2
 	continue
     fi
     width=$(sips -g pixelWidth $1 | grep -oE "[0-9\.]{1,}$")
@@ -28,5 +28,7 @@ for file in $@ ; do
     dpi=$(echo "$dpiw+$dpih" | bc -ql | cut -d'.' -f1)
     echo "$file: $width*$height:$dpi"
 done
+
+exit 0
 
 # EOF
diff --git a/bin/json b/bin/json
--- a/bin/json
+++ b/bin/json
@@ -1,31 +1,33 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # json -- json prettyfier from url or file
-# Copyright (C) 2012  Alan SCHNEIDER
-#                     <shk.schneider[at]gmail.com>
+# Copyright (C) 2012-2016  Alan SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
 # under certain conditions.
 #
 
-[ ! -x "$(which python)" ] && echo "E: python: command not found" >&2 && exit 1
-[ ! -x "$(which pygmentize)" ] && echo "E: pygmentize: command not found" >&2 && exit 1
+command -v python >/dev/null 2>&1 || { echo "E: python: command not found" >&2 ; exit 1 ; }
+command -v pygmentize >/dev/null 2>&1 || { echo "E: pygmentize: command not found" >&2 ; exit 1 ; }
 
 if [ $# -gt 0 ] ; then
-    [ ! -x "$(which curl)" ] && echo "E: curl: command not found" >&2 && exit 1
     for url in $@ ; do
 	echo "$url"
 	if [ -n "$(echo $url | egrep '^https?://')" ] ; then
+            command -v curl >/dev/null 2>&1 || { echo "E: curl: command not found" >&2 ; exit 1 ; }
 	    curl --silent "$url" | python -m json.tool | pygmentize -O style=monokai -f console256 -g
 	else
 	    cat "$url" | python -m json.tool | pygmentize -O style=monokai -f console256 -g
 	fi
     done
 else
-    read -u 0 JSON
-    echo $JSON
-    echo $JSON | python -m json.tool | pygmentize -O style=monokai -f console256 -g
+    read -u 0 json
+    echo $json
+    echo $json | python -m json.tool | pygmentize -O style=monokai -f console256 -g
 fi
+
+exit 0
 
 # EOF
diff --git a/bin/keep-screen-on b/bin/keep-screen-on
--- a/bin/keep-screen-on
+++ b/bin/keep-screen-on
@@ -1,18 +1,20 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # keep-screen-on -- tells X to never go to sleep
-# Copyright (C) 2012  Alan SCHNEIDER
-#                     <shk.schneider[at]gmail.com>
+# Copyright (C) 2012-2016  Alan SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
 # under certain conditions.
 #
 
-[ -z "`which xset`" ] && echo "keep-screen-on: command 'xset' not found" >&2 && exit 1
+command -v xset >/dev/null 2>&1 || { echo "E: xset: command not found" >&2 ; exit 1 ; }
 
 xset -dpms
 xset s off
 xset q | egrep '^\s+DPMS' | sed -r 's/^\s+//'
+
+exit 0
 
 # EOF
diff --git a/bin/keystore b/bin/keystore
--- a/bin/keystore
+++ b/bin/keystore
@@ -1,13 +1,15 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # keystore -- key store manager
-# Copyright (C) 2013  Alan SCHNEIDER
-#                     <shk.schneider[at]gmail.com>
+# Copyright (C) 2013-2016  Alan SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
 # under certain conditions.
 #
+
+command -v keytool >/dev/null 2>&1 || { echo "E: keytool: command not found" >&2 ; exit 1 ; }
 
 function usage() {
     echo "Usage: keystore <keystore> {l|list}" >&2
@@ -16,8 +18,6 @@ function usage() {
     echo "                           {can|changeAliasName <oldalias> <newalias>}" >&2
 }
 
-[ -z "$(which keytool)" ] && echo "E: keytool: command not found" >&2 && exit 1
-
 if [ $# -eq 0 ] ; then
     usage
     exit 1
@@ -25,7 +25,7 @@ fi
 
 keystore="$(readlink -f -- "$1" 2>/dev/null)"
 if [ -z "$keystore" ] || [ ! -f "$keystore" ] ; then
-    echo "E: $(basename $keystore): invalid keystore" >&2 && exit 1
+    echo "E: $(basename -- $keystore): invalid keystore" >&2 && exit 1
 fi
 
 case $2 in
@@ -52,5 +52,7 @@ case $2 in
         exit 1
         ;;
 esac
+
+exit 0
 
 # EOF
diff --git a/bin/netcraft b/bin/netcraft
--- a/bin/netcraft
+++ b/bin/netcraft
@@ -1,7 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # netcraft -- retrieve web server from URL
-# Copyright (C) 2010-2012  Alan SCHNEIDER
+# Copyright (C) 2010-2016  Alan SCHNEIDER
 #                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
@@ -9,8 +9,9 @@
 # under certain conditions.
 #
 
-[ -z "`cat /proc/net/arp | egrep '^[0-9]'`" ] && echo "netcraft: no network connection" >&2 && exit 1
-[ -z "`which curl`" ] && echo "netcraft: command 'curl' not found" && exit 1
+command -v curl >/dev/null 2>&1 || { echo "E: curl: command not found" >&2 ; exit 1 ; }
+
+[ -z "$(cat /proc/net/arp | egrep '^[0-9]')" ] && echo "E: no network connection" >&2 && exit 1
 
 if [ $# -eq 0 ] ; then
     echo "Usage: netcraft <host [...]>" >&2
@@ -46,8 +47,8 @@ for argv in $@ ; do
 	    continue
 	    ;;
 	*)
-	    if [ -n "`echo "$argv" | egrep '^[a-z]*://'`" ] ; then
-		echo "netcraft: unsupported protocol '"$(echo "$argv" | cut -d':' -f1)"'" >&2
+	    if [ -n "$(echo "$argv" | egrep '^[a-z]*://')" ] ; then
+		echo "E: unsupported protocol '$(echo "$argv" | cut -d':' -f1)'" >&2
 		continue
 	    fi
 	    get_server "http://$argv"
@@ -55,5 +56,7 @@ for argv in $@ ; do
 	    ;;
     esac
 done
+
+exit 0
 
 # EOF
diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,7 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # release -- outputs LSB-compliant OS release informations
-# Copyright (C) 2009-2012  Alan SCHNEIDER
+# Copyright (C) 2009-2016  Alan SCHNEIDER
 #                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
@@ -15,13 +15,16 @@ cpuinfo=$(cat /proc/cpuinfo | grep flags | grep ' lm ')
 [ -z "$cpuinfo" ] && cpu="x86" || cpu="x64"
 kernel=$(uname -sr | cut -d'-' -f1)
 
-if [ -z "`which lsb_release`" ] ; then
-    echo "release: command 'lsb_release' not found" >&2
+command -v lsb_release >/dev/null 2>&1
+if [ $? -ne 0 ] ; then
+    echo "W: lsb_release: command not found" >&2
     echo "$os $cpu [$lang] with $kernel"
 else
     distrib=$(lsb_release -i | awk '{printf $NF}')
-    version=$(lsb_release -sr)" \"$(exec lsb_release -sc | sed 's/^[a-z]/\U&/')"\"
+    version="$(lsb_release -sr) \"$(lsb_release -sc | sed 's/^[a-z]/\U&/')"\"
     echo "$os $distrib $version $cpu [$lang] with $kernel"
 fi
+
+exit 0
 
 # EOF
diff --git a/bin/supercopier b/bin/supercopier
--- a/bin/supercopier
+++ b/bin/supercopier
@@ -1,59 +1,61 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # supercopier -- cp with progress bar (with pv)
-# Copyright (C) 2010-211  Alan SCHNEIDER
-#                         <shk.schneider[at]gmail.com>
+# Copyright (C) 2010-2016  Alan SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
 # under certain conditions.
 #
 
-[ -z "`which pv`" ] && echo "supercopier: command 'pv' not found" >&2 && exit 1
+command -v pv >/dev/null 2>&1 || { echo "E: pv: command not found" >&2 ; exit 1 ; }
 
 [ $# -lt 2 ] && echo "Usage: supercopier <source [...]> <destination>" >&2 && exit 1
 
 function supercopier() {
     # 1: source
     # 2: destination
-    [ ! -e "$1" ] && echo "supercopier: $1: no such file or directory" >&2 && exit 1
-    [ ! -r "$1" ] && echo "supercopier: $1: premission denied" >&2 && exit 1
-    [ "$1" = "$2" ] && echo "supercopier: input file is output file" >&2 && exit 1
+    [ ! -e "$1" ] && echo "E: $1: no such file or directory" >&2 && exit 1
+    [ ! -r "$1" ] && echo "E: $1: premission denied" >&2 && exit 1
+    [ "$1" = "$2" ] && echo "E: input file is output file" >&2 && exit 1
     [ -d "$S1" -a ! -d "$2" ] && mkdir -p "$2"
-    OFFSET=$(echo "`tput cols` - `echo "$1$2 "| wc -c` - 6" | bc -q)
-    printf " * %s -> %s %${OFFSET}s\n" "$1" "$2" $(du -sh "$SOURCE" 2>/dev/null | awk '{print $1}')
-    find "$1" | sed "s#$1##g" | while read TARGET ; do
-	SOURCE=$1$TARGET
-	DESTINATION=$2$TARGET
-	if [ -d "$SOURCE" ] ; then
-	    [ ! -d "$DESTINATION" ] && mkdir -p "$DESTINATION"
-	elif [ -d "$DESTINATION" ] ; then
-	    echo "supercopier: $DESTINATION: is a directory" >&2 && sleep 1
+    offset=$(echo "$(tput cols) - $(echo "$1$2 "| wc -c) - 6" | bc -q)
+    printf " * %s -> %s %${offset}s\n" "$1" "$2" $(du -sh "$source" 2>/dev/null | awk '{print $1}')
+    find "$1" | sed "s#$1##g" | while read target ; do
+	source=$1$target
+	destination=$2$target
+	if [ -d "$source" ] ; then
+	    [ ! -d "$destination" ] && mkdir -p "$destination"
+	elif [ -d "$destination" ] ; then
+	    echo "E: $destination: is a directory" >&2 && sleep 1
 	else
-	    pv -pert "$SOURCE" > "$DESTINATION"
-	    [ $? -ne 0 ] && echo "supercopier: pv seems to have failed ($?)" >&2 && sleep 1
+	    pv -pert "$source" > "$destination"
+	    [ $? -ne 0 ] && echo "E: pv seems to have failed ($?)" >&2 && sleep 1
 	fi
     done
 }
 
-CMD_SOURCE=$(echo "$1" | sed "s#~#$HOME#g")
-CMD_DESTINATION=$(echo "$2" | sed "s#~#$HOME#g")
+cmd_source=$(echo "$1" | sed "s#~#$HOME#g")
+cmd_destination=$(echo "$2" | sed "s#~#$HOME#g")
 
 if [ $# -eq 2 ] ; then
-    SOURCE=$(readlink -f "$CMD_SOURCE")
-    DESTINATION=$(readlink -f "$CMD_DESTINATION")
-    supercopier "$SOURCE" "$DESTINATION/$(basename "$SOURCE")"
+    source=$(readlink -f -- "$cmd_source")
+    destination=$(readlink -f -- "$cmd_destination")
+    supercopier "$source" "$destination/$(basename -- "$source")"
 else
-    CMD_DESTINATION=$(while [ $# -gt 1 ] ; do shift; done ; echo $1)
+    cmd_destination=$(while [ $# -gt 1 ] ; do shift; done ; echo $1)
     I=1
-    for SOURCE in "$@" ; do
-	SOURCE=$(readlink -f "$SOURCE")
-	DESTINATION=$CMD_DESTINATION/$(basename "$SOURCE")
-	DESTINATION=$(readlink -f "$DESTINATION")
-	supercopier "$SOURCE" "$DESTINATION"
+    for source in "$@" ; do
+	source=$(readlink -f -- "$source")
+	destination=$cmd_destination/$(basename -- "$source")
+	destination=$(readlink -f -- "$destination")
+	supercopier "$source" "$destination"
 	I=$(($I + 1))
 	[ $I -eq $# ] && break
     done
 fi
+
+exit 0
 
 # EOF
diff --git a/bin/whatismyip b/bin/whatismyip
--- a/bin/whatismyip
+++ b/bin/whatismyip
@@ -1,7 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # whatismyip -- retrieve your internal/external IP from command line
-# Copyright (C) 2010-2012  Alan SCHNEIDER
+# Copyright (C) 2010-2016  Alan SCHNEIDER
 #                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
@@ -9,16 +9,18 @@
 # under certain conditions.
 #
 
-ifconfig=$(which ifconfig 2>/dev/null)
+ifconfig=$(command -v ifconfig 2>/dev/null)
 [ -z "$ifconfig" ] && ifconfig="/sbin/ifconfig"
-
-[ ! -x "$ifconfig" ] && echo "whatismyip: command 'ifconfig' not found" >&2 && exit 1
-[ -z "`which curl`" ] && echo "whatismyip: command 'curl' not found" >&2 && exit 1
+[ ! -x "$ifconfig" ] && echo "E: ifconfig: command not found" >&2 && exit 1
+command -v curl >/dev/null 2>&1 || { echo "E: curl: command not found" >&2 ; exit 1 ; }
 
 internal=$($ifconfig  | grep "inet addr:" | grep Bcast | awk '{print $2}' | cut -d':' -f2)
-external=$(curl -s ifconfig.me/ip)
-echo "$internal $external"
+[ -z "$internal" ] && exit 1
+echo "$internal"
+external=$(curl -s http://ipecho.net/plain)
+[ -z "$external" ] && exit 1
+echo "$external"
 
-# Todo: retrieve interface
+exit 0
 
 # EOF
