Massive rework on variable names (1/2)

diff --git a/bin/big b/bin/big
--- a/bin/big
+++ b/bin/big
@@ -15,14 +15,14 @@ if [ $# -ne 2 ] ; then
     exit 1
 fi
 
-DIR=$(readlink -f "$1")
-SIZE=$(echo "$2" | tr "[a-z]" "[A-Z]" | egrep "^[0-9]+[MGT]?$")
-[ ! -e "$DIR" ] && echo "big: $DIR: no such file or directory" >&2 && exit 1
-[ ! -d "$DIR" ] && echo "big: $DIR: not a directory" >&2 && exit 1
-[ ! -r "$DIR" ] && echo "big: $DIR: permission denied" >&2 && exit 1
-[ -z "$SIZE" ] && echo "big: invalid size" >&2 && exit 1
+dir=$(readlink -f "$1")
+size=$(echo "$2" | tr "[a-z]" "[A-Z]" | egrep "^[0-9]+[MGT]?$")
+[ ! -e "$dir" ] && echo "big: $dir: no such file or directory" >&2 && exit 1
+[ ! -d "$dir" ] && echo "big: $dir: not a directory" >&2 && exit 1
+[ ! -r "$dir" ] && echo "big: $dir: permission denied" >&2 && exit 1
+[ -z "$size" ] && echo "big: invalid size" >&2 && exit 1
 
-echo " * Searching in $DIR for files bigger than ${SIZE}B..."
-find "$DIR" -type f -size +$SIZE -exec ls -lh {} \; 2>/dev/null | sed -r 's/ +/ /g' | cut -d' ' -f5,9-
+echo " * Searching in '$dir' for files bigger than ${size}B..."
+find "$dir" -type f -size +$size -exec ls -lh {} \; 2>/dev/null | sed -r 's/ +/ /g' | cut -d' ' -f5,9-
 
 # EOF
diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -10,69 +10,69 @@
 #
 
 function cmd() {
-    for BIN in "$1" ; do
-	[ -n "`which $BIN`" ] && echo "extract: command '$BIN' not found" >&2 && return 1
+    for bin in "$1" ; do
+	[ -n "`which $bin`" ] && echo "extract: command '$bin' not found" >&2 && return 1
     done
     return 0
 }
 
 function extract() {
-    echo " * Extracting `basename $FILE` to `pwd`..."
-    case "$FILE" in
-	*.tar)			cmd "tar" && tar xvf "$FILE" ;;
-	*.tar.bz2|*.tbz2)	cmd "tar" && tar xvjf "$FILE" ;;
-	*.tar.gz|*.tgz)		cmd "tar" && tar xvzf "$FILE" ;;
-	*.tar.xz|*.txz)		cmd "tar" && tar xvJf "$FILE" ;;
-	*.tar.lzma|*.tlzma)	cmd "tar" && tar --lzma xf "$FILE" ;;
+    echo " * Extracting `basename $file` to `pwd`..."
+    case "$file" in
+	*.tar)			cmd "tar" && tar xvf "$file" ;;
+	*.tar.bz2|*.tbz2)	cmd "tar" && tar xvjf "$file" ;;
+	*.tar.gz|*.tgz)		cmd "tar" && tar xvzf "$file" ;;
+	*.tar.xz|*.txz)		cmd "tar" && tar xvJf "$file" ;;
+	*.tar.lzma|*.tlzma)	cmd "tar" && tar --lzma xf "$file" ;;
 	*.tar.*|*.t*)		cmd "tar" && \
 	    echo "W: Using generic tar decompression -- might not work" && \
-	    tar xf "$FILE" ;;
-	*.bz2)			cmd "bunzip2" && bunzip2 "$FILE" ;;
-	*.rar)			cmd "unrar" && unrar x "$FILE" ;;
-	*.gz)			cmd "gunzip" && gunzip "$FILE" ;;
-	*.zip)			cmd "unzip" && unzip "$FILE" ;;
-	*.Z)			cmd "uncompress" && uncompress "$FILE" ;;
-	*.7z)			cmd "p7zip" && p7zip -d "$FILE" ;;
-	*.xz)			cmd "unxz" && unxz "$FILE" ;;
-	*.exe|*.cab)		cmd "cabextract" && cabextract "$FILE" ;;
-	*.ace)			cmd "unace" && unace e "$FILE" ;;
-	*.rpm)			cmd "rpm2cpio cpio" && rpm2cpio "$FILE" | cpio -idmv ;;
-	*.iso)			cmd "poweriso" && poweriso extract "$FILE" / ;;
+	    tar xf "$file" ;;
+	*.bz2)			cmd "bunzip2" && bunzip2 "$file" ;;
+	*.rar)			cmd "unrar" && unrar x "$file" ;;
+	*.gz)			cmd "gunzip" && gunzip "$file" ;;
+	*.zip)			cmd "unzip" && unzip "$file" ;;
+	*.Z)			cmd "uncompress" && uncompress "$file" ;;
+	*.7z)			cmd "p7zip" && p7zip -d "$file" ;;
+	*.xz)			cmd "unxz" && unxz "$file" ;;
+	*.exe|*.cab)		cmd "cabextract" && cabextract "$file" ;;
+	*.ace)			cmd "unace" && unace e "$file" ;;
+	*.rpm)			cmd "rpm2cpio cpio" && rpm2cpio "$file" | cpio -idmv ;;
+	*.iso)			cmd "poweriso" && poweriso extract "$file" / ;;
 #	*.deb)			cmd "dpkg-deb" && dpkg-deb -x "$FILE" ;;
-	*.deb)			cmd "ar" && ar xv "$FILE"
+	*.deb)			cmd "ar" && ar xv "$file"
             # this one also extract the tarballs witin the .deb
 	    [ $? -ne 0 ] && continue
-	    ar t "$FILE" | grep -E '\.tar\.gz$' | \
-		while read SUBFILE ; do
-		extract "$SUBFILE"
+	    ar t "$file" | grep -E '\.tar\.gz$' | \
+		while read subfile ; do
+		extract "$subfile"
 	    done
 	    ;;
 	*)
 	    cmd "tar" && \
 		echo "W: Using generic tar decompression -- will most likely not work" >&2 && \
-		tar xf "$FILE"
+		tar xf "$file"
 	    [ $? -ne 0 ] && cmd "p7zip" && \
 		echo "W: Using generic p7zip decompression -- will most likely not work" >&2 && \
-		p7zip -d "$FILE";;
+		p7zip -d "$file";;
     esac
 }
 
 [ $# -eq 0 ] && echo "Usage: extract <file [...]>" >&2 && exit 1
 
-for FILE in "$@" ; do
-    [ ! -e "$FILE" ] && echo "extract: $FILE: no such file or directory" >&2 && exit 1
-    [ -d "$FILE" ] && echo "extract: $FILE: is a directory" >&2 && exit 1
-    [ ! -r "$FILE" ] && echo "extract: $FILE: permission denied" >&2 && exit 1
-    FILE=$(readlink -f "$FILE")
-    NAME=$(basename "$FILE" | sed -r 's/(\.[a-zZ2]{2,3})?\.[a-zZ2]{1,4}$//')
-    if [ -d "$NAME" ] ; then
-	echo -n "   Directory \`$NAME' exists. Overwite [Y/n]? "
-	read REP
-	[ "_$REP" = "_n" ] && continue
-	rm -rf "$NAME"
+for file in "$@" ; do
+    [ ! -e "$file" ] && echo "extract: $file: no such file or directory" >&2 && exit 1
+    [ -d "$file" ] && echo "extract: $file: is a directory" >&2 && exit 1
+    [ ! -r "$file" ] && echo "extract: $file: permission denied" >&2 && exit 1
+    file=$(readlink -f "$file")
+    name=$(basename "$file" | sed -r 's/(\.[a-zZ2]{2,3})?\.[a-zZ2]{1,4}$//')
+    if [ -d "$name" ] ; then
+	echo -n "   Directory \`$name' exists. Overwite [Y/n]? "
+	read rep
+	[ "_$rep" = "_n" ] && continue
+	rm -rf "$name"
     fi
     # prevent tab-bombs
-    mkdir "$NAME" && cd "$NAME"
+    mkdir "$name" && cd "$name"
     extract
 done
 
diff --git a/bin/git-amend b/bin/git-amend
--- a/bin/git-amend
+++ b/bin/git-amend
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# git-ammend -- change an author on git commits
+# git-amend -- change an author on git commits
 # Copyright (C) 2012  Alan SCHNEIDER
 #                     <shk.schneider[at]gmail.com>
 #
@@ -11,15 +11,15 @@
 # under certain conditions.
 #
 
-[ -z "`which git`" ] && echo "git-ammend: command 'git' not found" >&2 && exit 1
+[ -z "`which git`" ] && echo "git-amend: command 'git' not found" >&2 && exit 1
 
 function usage() {
-    echo "Usage: git-ammend [-a|--all]" >&2
+    echo "Usage: git-amend [-a|--all]" >&2
     exit 1
 }
 
-DIR=$(git rev-parse --git-dir 2>/dev/null)
-[ -z "$DIR" ] && echo "git-ammend: not a git repository" >&2 && exit 1
+dir=$(git rev-parse --git-dir 2>/dev/null)
+[ -z "$dir" ] && echo "git-amend: not a git repository" >&2 && exit 1
 
 [ $# -gt 1 ] && usage
 
@@ -28,33 +28,33 @@ case $1 in
 	echo "I: This script will only affect the last commit"
 	echo "I: last author was: "$(git log -n 1 | sed -n '2p' | cut -d' ' -f2-)
 	echo -n "New Author Name: "
-	read NEW_NAME
-	[ -z "$NEW_NAME" ] && echo "Canceled" && exit 1
+	read new_name
+	[ -z "$new_name" ] && echo "Canceled" && exit 1
 	echo -n "New Author Email: "
-	read NEW_EMAIL
-	[ -z "$NEW_EMAIL" ] && echo "Canceled" && exit 1
-	git commit --amend --author="$NEW_NAME <$NEW_EMAIL>"
+	read new_email
+	[ -z "$new_email" ] && echo "Canceled" && exit 1
+	git commit --amend --author="$new_name <$new_email>"
 	echo "W: commiter's name is still unchanged for futur commits"
 	;;
     "-a"|"--all")
 	echo "W: this script will affect ALL commits"
 	echo "I: last author was: "$(git log -n 1 | sed -n '2p' | cut -d' ' -f2-)
 	echo -n "Old Author Name: "
-	read OLD_NAME
-	[ -z "$OLD_NAME" ] && echo "Canceled" && exit 1
+	read old_name
+	[ -z "$old_name" ] && echo "Canceled" && exit 1
 	echo -n "New Author Name: "
-	read NEW_NAME
-	[ -z "$NEW_NAME" ] && echo "Canceled" && exit 1
+	read new_name
+	[ -z "$new_name" ] && echo "Canceled" && exit 1
 	echo -n "New Author Email: "
-	read NEW_EMAIL
-	[ -z "$NEW_EMAIL" ] && echo "Canceled" && exit 1
+	read new_email
+	[ -z "$new_email" ] && echo "Canceled" && exit 1
 	git filter-branch -f --commit-filter '
-          aif [ "$GIT_COMMITTER_NAME" = "$OLD_NAME" ];
+          if [ "$GIT_COMMITTER_NAME" = "$old_name" ];
           then
-                  GIT_COMMITTER_NAME="$NEW_NAME";
-                  GIT_AUTHOR_NAME="$NEW_NAME";
-                  GIT_COMMITTER_EMAIL="$NEW_EMAIL";
-                  GIT_AUTHOR_EMAIL="$NEW_EMAIL";
+                  GIT_COMMITTER_NAME="$new_name";
+                  GIT_AUTHOR_NAME="$new_name";
+                  GIT_COMMITTER_EMAIL="$new_email";
+                  GIT_AUTHOR_EMAIL="$new_email";
                   git commit-tree "$@";
           else
                   git commit-tree "$@";
