bin/json: uses jq(1)

diff --git a/bin/json b/bin/json
--- a/bin/json
+++ b/bin/json
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
 # json -- json prettyfier from url or file
-# Copyright (C) 2012-2016  Alan SCHNEIDER
+# Copyright (C) 2012-2017  Alan SCHNEIDER
 #                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
@@ -9,23 +9,22 @@
 # under certain conditions.
 #
 
-command -v python >/dev/null 2>&1 || { echo "E: python: command not found" >&2 ; exit 1 ; }
-command -v pygmentize >/dev/null 2>&1 || { echo "E: pygmentize: command not found" >&2 ; exit 1 ; }
+command -v jq >/dev/null 2>&1 || { echo "E: jq: command not found" >&2 ; exit 1 ; }
 
 if [ $# -gt 0 ] ; then
     for url in $@ ; do
 	echo "$url"
 	if [ -n "$(echo $url | egrep '^https?://')" ] ; then
             command -v curl >/dev/null 2>&1 || { echo "E: curl: command not found" >&2 ; exit 1 ; }
-	    curl --silent "$url" | python -m json.tool | pygmentize -O style=monokai -f console256 -g
+	    curl --silent "$url" | jq .
 	else
-	    cat "$url" | python -m json.tool | pygmentize -O style=monokai -f console256 -g
+	    cat "$url" | jq .
 	fi
     done
 else
     read -u 0 json
     echo $json
-    echo $json | python -m json.tool | pygmentize -O style=monokai -f console256 -g
+    echo $json | jq .
 fi
 
 exit 0
