bin/whatismyip: forget ifconfig, uses hostname -I and ipify.org

diff --git a/bin/whatismyip b/bin/whatismyip
--- a/bin/whatismyip
+++ b/bin/whatismyip
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
 # whatismyip -- retrieve your internal/external IP from command line
-# Copyright (C) 2010-2016  Alan SCHNEIDER
+# Copyright (C) 2010-2017  Alan SCHNEIDER
 #                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
@@ -9,17 +9,14 @@
 # under certain conditions.
 #
 
-ifconfig=$(command -v ifconfig 2>/dev/null)
-[ -z "$ifconfig" ] && ifconfig="/sbin/ifconfig"
-[ ! -x "$ifconfig" ] && echo "E: ifconfig: command not found" >&2 && exit 1
-command -v curl >/dev/null 2>&1 || { echo "E: curl: command not found" >&2 ; exit 1 ; }
-
-internal=$($ifconfig  | grep "inet addr:" | grep Bcast | awk '{print $2}' | cut -d':' -f2)
+internal=$(hostname -I)
 [ -z "$internal" ] && exit 1
 echo "$internal"
-external=$(curl -s http://ipecho.net/plain)
-[ -z "$external" ] && exit 1
-echo "$external"
+
+command -v curl >/dev/null 2>&1 || { echo "E: curl: command not found" >&2 ; exit 1 ; }
+
+external=$(curl -s https://api.ipify.org)
+[ -n "$external" ] && echo "$external"
 
 exit 0
 
