Updated headers and optimizations New scripts: 64bits, dos2unix, lastlogin, passgen, revcat, power_off and network

diff --git a/big b/big
--- a/big
+++ b/big
@@ -1,7 +1,12 @@
 #!/bin/bash
 #
-# (C) 2010,2011 - Alan SCHNEIDER <shk.schneider@gmail.com>
-# Distributed under GNU GPLv2+
+# big -- list big files
+# Copyright (C) 2010-2011  Alan "Shtark" SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
+#
+# This program comes with ABSOLUTELY NO WARRANTY.
+# This is free software, and you are welcome to redistribute it
+# under certain conditions.
 #
 
 if [ $# -ne 2 ] ; then
@@ -12,10 +17,10 @@ fi
 
 DIR=$(readlink -f "$1")
 SIZE=$(echo "$2" | tr "[a-z]" "[A-Z]" | egrep "^[0-9]+[MGT]?$") 
-[ ! -e "$DIR" ] && echo "E: $DIR: No such file or directory" >&2 && exit 1
-[ ! -d "$DIR" ] && echo "E: $DIR: Not a directory" >&2 && exit 1
-[ ! -r "$DIR" ] && echo "E: $DIR: Permission denied" >&2 && exit 1
-[ "_$SIZE" = "_" ] && echo "E: Invalid size" >&2 && exit 1
+[ ! -e "$DIR" ] && echo "E: $DIR: No such file or directory." >&2 && exit 1
+[ ! -d "$DIR" ] && echo "E: $DIR: Not a directory." >&2 && exit 1
+[ ! -r "$DIR" ] && echo "E: $DIR: Permission denied." >&2 && exit 1
+[ "_$SIZE" = "_" ] && echo "E: Invalid size." >&2 && exit 1
 
 echo " * Searching in $DIR for files bigger than ${SIZE}B..."
 find "$DIR" -type f -size +$SIZE -exec ls -lh {} \; 2>/dev/null | sed -r 's/ +/ /g' | cut -d' ' -f5,9-
diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -22,7 +22,7 @@
 
 function cmd() {
     for BIN in "$1" ; do
-	[ "_`which $BIN`" = "_" ] && echo "E: $BIN: Command not found" >&2 && return 1
+	[ "_`which $BIN`" = "_" ] && echo "E: $BIN: Command not found." >&2 && return 1
     done
     return 0
 }
@@ -82,7 +82,7 @@ for FILE in "$@" ; do
 	[ "_$REP" = "_n" ] && continue
 	rm "$NAME" -rf
     fi
-#   prevent from tab-bombs
+    # prevent tab-bombs
     mkdir "$NAME" && cd "$NAME"
     extract
 done
diff --git a/gnome-menu b/gnome-menu
--- a/gnome-menu
+++ b/gnome-menu
@@ -1,10 +1,15 @@
 #!/bin/bash
 #
-# (C) 2010 - Alan SCHNEIDER <shk.schneider@gmail.com>
-# Distributed under GNU GPLv2+
+# gnome-menu -- use GNOME2 menu style
+# Copyright (C) 2010  Alan "Shtark" SCHNEIDER
+#                     <shk.schneider[at]gmail.com>
+#
+# This program comes with ABSOLUTELY NO WARRANTY.
+# This is free software, and you are welcome to redistribute it
+# under certain conditions.
 #
 
-[ "_`which gconftool`" = "_" ] && echo "E: gconftool: No such file or directory" >&2 && exit 1
+[ "_`which gconftool`" = "_" ] && echo "E: gconftool: Command not found." >&2 && exit 1
 
 echo " * button_layout = menu:minimize,maximize,close"
 gconftool-2 --set /apps/metacity/general/button_layout --type string "menu:minimize,maximize,close"
diff --git a/root_only/ping-apt b/root_only/ping-apt
--- a/root_only/ping-apt
+++ b/root_only/ping-apt
@@ -1,4 +1,5 @@
 #!/bin/bash
+#
 # ping-apt -- ping your apt repositories
 # Copyright (C) 2010  Alan "Shtark" SCHNEIDER
 #                     <shk.schneider[at]gmail.com>
@@ -10,6 +11,8 @@
 
 OK=$(echo -e "[ \033[0;32mok\033[0;0m ]")
 KO=$(echo -e "[ \033[0;31mko\033[0;0m ]")
+
+[ "_`which curl`" = "_" ] && echo "E: curl: Command not found" >&2 && exit 1
 
 function ping_apt() {
     HTTP_STATUS=$(curl -I "$URL" 2>/dev/null | grep -E '^HTTP' | tr -d "\r" | awk '{print "HTTP/"$2}')
@@ -30,8 +33,6 @@ function ping_apt() {
 	printf "%${OFFSET}s\n" "$KO"
     fi
 }
-
-[ "_`which curl`" = "_" ] && echo "E: which: Command not found" >&2 && exit 1
 
 if [ $# -ne 0 ] ; then
     FILE=$(readlink -f "$1")
