apt: added status, keep and fixes

diff --git a/sbin/apt b/sbin/apt
--- a/sbin/apt
+++ b/sbin/apt
@@ -9,6 +9,15 @@
 # under certain conditions.
 #
 # version history:
+#	v2.89  jan 2012  cmd: keep
+#	v2.88  jan 2012  fix on file (duplicates)
+#	v2.87  jan 2012  fix on file (duplicates)
+#	v2.86  jan 2012  allow status/search/show to have 1+ args
+#	v2.85  jan 2012  cmd: status (req. apt-show-versions)
+#	v2.84  jan 2012  minor fix on depends
+#	v2.83  jan 2012  added check_package which return 0 on success
+#	v2.82  jan 2012  minor fixes
+#	v2.81  jan 2012  better output
 #	v2.80  nov 2011  display release in repositories command
 #	v2.70  nov 2011  run only once install,reinstall,remove,purge,download,source
 #	v2.60  nov 2011  policy usage changed (alone or 1+ arguments)
@@ -38,6 +47,9 @@
 #	v0.3   oct 2011  cmd: update, upgrade, remove, purge, reinstall
 #	v0.2   oct 2011  handles aptitude or apt-get
 #	v0.1   oct 2011  skeleton and parser
+#
+# bugs:
+#	wc -c counts special chars (with accents) twice
 #
 
 set -f
@@ -92,8 +104,9 @@ function usage() {
     echo "       {--help|--version|--author}" >&2
     echo "       update" >&2
     echo "       upgrade" >&2
-    echo "       search <PACKAGE>" >&2
-    echo "       show <PACKAGE>" >&2
+    echo "       status <PACKAGE ...>" >&2
+    echo "       search <PACKAGE ...>" >&2
+    echo "       show <PACKAGE ...>" >&2
     echo "       file <FILE>" >&2
     echo "       install <PACKAGE ...>" >&2
     echo "       reinstall <PACKAGE ...>" >&2
@@ -107,11 +120,47 @@ function usage() {
     echo "       architecture" >&2
     echo "       repositories" >&2
     echo "       available" >&2
+    echo "       keep" >&2
+}
+
+function do_status() {
+    LINE=$(apt-show-versions --package=$PACKAGE)
+    MSTATUS=$(dpkg -l $PACKAGE 2>/dev/null | tail -1 | cut -c1,2)
+    [ -z "$MSTATUS" ] && MSTATUS=" "
+    check_package $PACKAGE
+    if [ $? -ne 0 ] ; then
+	STATUS="not available"
+	case $REVERSE in
+            1)	printf "%s \e[7m%s\e[0m - %s\n" "$MSTATUS" "$PACKAGE" "$STATUS" ;;
+            *)	printf "%s %s - %s\n" "$MSTATUS" "$PACKAGE" "$STATUS" ;;
+	esac
+    elif [ -z "`echo $LINE | egrep "^$PACKAGE/"`" ] ; then
+	STATUS="not installed"
+	case $REVERSE in
+	    1)	printf "%s \e[7m%s\e[0m - %s\n" "$MSTATUS" "$PACKAGE" "$STATUS" ;;
+	    *)	printf "%s %s - %s\n" "$MSTATUS" "$PACKAGE" "$STATUS" ;;
+	esac
+    else
+	if [ -z "`apt-show-versions -u | egrep "^$PACKAGE/"`" ] ; then
+	    STATUS="installed and up-to-date"
+	else
+	    STATUS="installed but updatable"
+	fi
+	REPO=$(echo $LINE | cut -d'/' -f2- | cut -d' ' -f1)
+	VERSION=$(echo $LINE | rev | cut -d' ' -f1 | rev)
+	COLUMNS=$(echo "`tput cols`-`echo "$MSTATUS $PACKAGE - $STATUS" | wc -c`+1" | bc -q)
+	case $REVERSE in
+	    1)	printf "%s \e[7m%s\e[0m - %s%${COLUMNS}s\n" "$MSTATUS" "$PACKAGE" "$STATUS" "$REPO/$VERSION" ;;
+	    *)	printf "%s %s - %s%${COLUMNS}s\n" "$MSTATUS" "$PACKAGE" "$STATUS" "$REPO/$VERSION" ;;
+	esac
+    fi
 }
 
 function do_search() {
+    N=0
     PACKAGE=$1
     while read LINE ; do
+	N=$(($N + 1))
 	PACKAGE=$(echo $LINE | cut -d' ' -f1)
 	VERSION=$(echo $LINE | cut -d' ' -f2)
 	SIZE=$(echo $LINE | awk '{print $NF}')
@@ -125,30 +174,33 @@ function do_search() {
 	else
 	    SIZE="$SIZE kB"
 	fi
-	STATUS=$(dpkg -l $PACKAGE 2>/dev/null | tail -1 | cut -c2)
+	STATUS=$(dpkg -l $PACKAGE 2>/dev/null | tail -1 | cut -c1,2)
 	[ -z "$STATUS" ] && STATUS=" "
 	COLUMNS=$(echo "`tput cols`-`echo "$STATUS $PACKAGE - $DESCRIPTION" | wc -c`-`echo "$VERSION - $SIZE" | wc -c`+1" | bc -q)
 	case $REVERSE in
             1)	printf "%s \e[7m%s\e[0m - %s%${COLUMNS}sv%s - \e[1m%s\e[0m\n" "$STATUS" "$PACKAGE" "$DESCRIPTION" " " "$VERSION" "$SIZE" ;;
             *)	printf "%s %s - %s%${COLUMNS}sv%s - %s\n" "$STATUS" "$PACKAGE" "$DESCRIPTION" " " "$VERSION" "$SIZE" ;;
 	esac
-    done < <(apt-cache show $PACKAGE \
+    done < <(apt-cache show $PACKAGE 2>/dev/null \
 	| egrep '^(Package|Version|Description|Size)' \
 	| sed "s#Package: #\n#g" \
 	| sed "s#Version: ##g" \
 	| sed "s#Description: ##g" \
 	| sed "s#Size: ##g" \
 	| sed '1d' | tr "\n" "@" | sed "s#@@#\n#g" | tr '@' ' ' | sed -r "s#\s\$#\n#")
+    [ $N -eq 0 ] && echo "No package found for \`$PACKAGE'" >&2
 }
 
 function do_depends() {
     PACKAGE=$1
-    D=$(apt-cache depends -i $PACKAGE | sed '1d' | sed -r 's#\s+Depends: ##' | wc -l)
+    check_package $PACKAGE
+    [ $? -ne 0 ] && echo "E: $PACKAGE: Package not found" >&2 && return
+    D=$(apt-cache depends -i $PACKAGE | sed '1d' | sed -r 's#\s+\w+: ##' | wc -l)
     case $REVERSE in
 	1)	echo -ne "\e[7m$PACKAGE\e[0m (\e[1m$D\e[0m) " ;;
 	*)	echo -n "$PACKAGE ($D) " ;;
     esac
-    DEPENDS=$(apt-cache depends -i $PACKAGE | sed '1d' | sed -r "s#\s+Depends: ##")
+    DEPENDS=$(apt-cache depends -i $PACKAGE | sed '1d' | sed -r "s#\s+\w+: ##")
     echo $DEPENDS
 }
 
@@ -174,6 +226,8 @@ function do_size() {
 }
 
 function do_policy() {
+    check_package $PACKAGE
+    [ $? -ne 0 ] && echo "E: $PACKAGE: Package not found" >&2 && return
     while read LINE ; do
 	[ $REVERSE -eq 1 ] && echo -ne "\e[7m$PACKAGE\e[0m " || echo -n "$PACKAGE "
 	PRIOR=$(echo $LINE | cut -d' ' -f1)
@@ -227,6 +281,13 @@ function do_repositories() {
     fi
 }
 
+function check_package() {
+    while read TMP ; do
+	return 0
+    done < <(apt-cache policy $1)
+    return 1
+}
+
 #
 ## Checking arguments
 #
@@ -239,42 +300,59 @@ case $1 in
 	[ $# -ne 1 ] && echo "E: Too many arguments" >&2 && usage && exit 1
 	;;
     "install"|"reinstall"|"remove"|"purge"|"download"|"source")
-	[ `id -u` -ne 0 ] && echo "E: `id -un`: are you root?" >&2 && exit 1
-	[ $# -lt 2 ] && echo "E: Too few arguments" >&2 && usage && exit 1
-	[ -z "$APT" ] && echo "E: $1: That Command requiers `echo $BINS | sed 's/ / or /g'`" >&2 && exit 1
-	[ $1 = "source" -a $APT != "apt-get" ] && echo "E: source: That Command requiers apt-get" >&2 && exit 1
+	[ `id -u` -ne 0 ] && echo "E: $1: Are you root, `id -un`?" >&2 && exit 1
+	[ $# -lt 2 ] && echo "E: $1: Too few arguments" >&2 && usage && exit 1
+	[ -z "$APT" ] && echo "E: $1: That command requiers `echo $BINS | sed 's/ / or /g'`" >&2 && exit 1
+	[ $1 = "source" -a $APT != "apt-get" ] && echo "E: $1: That Command requiers apt-get" >&2 && exit 1
 	;;
-    "search"|"show"|"file"|"depends"|"policy")
-	[ ! -x "`which apt-cache`" ] && echo "E: apt-cache: Command not found" >&2 && exit 1
-	[ $1 = "policy" -a $# -lt 1 ] && echo "E: Too few arguments" >&2 && usage && exit 1
-	[ $1 != "policy" -a $# -lt 2 ] && echo "E: Too few arguments" >&2 && usage && exit 1
-	[ $1 != "policy" -a $# -gt 2 ] && echo "E: Too many arguments" >&2 && usage && exit 1
-	[ $1 = "file" -a ! -x "`which dpkg`" ] && echo "E: dpkg: Command not found" >&2 && exit 1
-	[ $1 = "file" -a ! -x "`which apt-cache`" ] && echo "E: apt-cache: Command not found" >&2 && exit 1
+    "status"|"search"|"show")
+	[ $1 != "status" -a ! -x "`which apt-cache`" ] && echo "E: $1: That command requiers apt-cache" >&2 && exit 1
+	[ $1 = "status" -a ! -x "`which apt-show-versions`" ] && echo "E: $1: That command requiers apt-show-versions" >&2 && exit 1
+	[ $# -lt 1 ] && echo "E: $1: Too few arguments" >&2 && usage && exit 1
+	;;
+    "file")
+	[ ! -x "`which apt-cache`" ] && echo "E: $1: That command requiers apt-cache" >&2 && exit 1
+	[ $# -lt 2 ] && echo "E: $1: Too few arguments" >&2 && usage && exit 1
+	[ $# -gt 2 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
+	[ ! -x "`which dpkg`" ] && echo "E: $1: That command requiers dpkg" >&2 && exit 1
+	[ ! -x "`which apt-cache`" ] && echo "E: $1: That command requiers apt-cache" >&2 && exit 1
+	;;
+    "depends")
+	[ ! -x "`which apt-cache`" ] && echo "E: $1: That command requiers apt-cache" >&2 && exit 1
+	[ $# -lt 2 ] && echo "E: $1: Too few arguments" >&2 && usage && exit 1
+	[ $# -gt 2 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
+	;;
+    "policy")
+	[ ! -x "`which apt-cache`" ] && echo "E: $1: That command requiers apt-cache" >&2 && exit 1
+	[ $# -lt 1 ] && echo "E: $1: Too few arguments" >&2 && usage && exit 1
 	;;
     "size")
-	[ ! -x "`which dpkg-query`" ] && echo "E: dpkg-query: Command not found" >&2 && exit 1
-	[ $# -gt 2 ] && echo "E: Too many arguments" >&2 && usage && exit 1
+	[ ! -x "`which dpkg-query`" ] && echo "E: $1: That command requiers dpkg-query" >&2 && exit 1
+	[ $# -gt 2 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
 	[ -n "`echo "$2" | tr -d '[0-9]'`" ] && echo "E: $1: Not a number" >&2 && usage && exit 1
 	;;
     "architecture")
-	[ ! -x "`which dpkg`" ] && echo "E: dpkg: Command not found" >&2 && exit 1
-	[ $# -gt 1 ] && echo "E: Too many arguments" >&2 && usage && exit 1
+	[ ! -x "`which dpkg`" ] && echo "E: $1: That command requiers dpkg" >&2 && exit 1
+	[ $# -gt 1 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
 	;;
     "available")
-	[ ! -x "`which apt-show-versions`" ] && echo "E: apt-show-versions: Command not found" >&2 && exit 1
-	[ $# -gt 1 ] && echo "E: Too many arguments" >&2 && usage && exit 1
+	[ ! -x "`which apt-show-versions`" ] && echo "E: $1: That command requiers apt-show-versions" >&2 && exit 1
+	[ $# -gt 1 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
+	;;
+    "keep")
+	[ $APT != "aptitude" ] && echo "E: $1: That command requiers aptitude" >&2 && exit 1
+	[ $# -gt 1 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
 	;;
     "repositories")
-	[ ! -x "`which dpkg`" ] && echo "E: dpkg: Command not found" >&2 && exit 1
-	[ -z "`find /etc/apt -type f -name "*.list"`" ] && echo "E: /etc/apt: No .list file found" >&2 && exit 1
-	[ ! -e /var/lib/apt/lists ] && echo "E: /var/lib/apt/lists: No such file or directory" >&2 && exit 1
-	[ ! -d /var/lib/apt/lists ] && echo "E: /var/lib/apt/lists: Not a directory" >&2 && exit 1
+	[ ! -x "`which dpkg`" ] && echo "E: $1: That command requiers dpkg" >&2 && exit 1
+	[ -z "`find /etc/apt -type f -name "*.list"`" ] && echo "E: $1: No .list file found in /etc/apt/" >&2 && exit 1
+	[ ! -e /var/lib/apt/lists ] && echo "E: $1: /var/lib/apt/lists not found" >&2 && exit 1
+	[ ! -d /var/lib/apt/lists ] && echo "E: $1: /var/lib/apt/lists not found" >&2 && exit 1
 	;;
     "--help"|"--version"|"--author")
 	[ -z "`readlink -f "$0" | egrep '^/'`" ] && exit 1
 	;;
-    *)	echo "E: Unknown argument \`$1'" >&2 && usage && exit 1 ;;
+    *)	echo "E: $1: Unknown argument" >&2 && usage && exit 1 ;;
 esac
 
 #
@@ -291,14 +369,30 @@ case $1 in
 	    *)		$APT upgrade ;;
 	esac
 	;;
+    "status")
+	shift
+	for PACKAGE in $@ ; do
+	    do_status $PACKAGE
+	done
+	;;
     "search")
-	do_search $2
+	shift
+	for PACKAGE in $@ ; do
+	    do_search $PACKAGE
+	done
 	;;
     "show")
-	apt-cache show $2 | sed '/^$/d'
+	shift
+	N=0
+	for PACKAGE in $@ ; do
+	    [ $N -gt 0 ] && echo ""
+	    N=$(($N + 1))
+	    check_package $PACKAGE
+	    [ $? -eq 0 ] && apt-cache show $PACKAGE 2>/dev/null | sed '/^$/d' || echo "E: $PACKAGE: Package not found" >&2
+	done
 	;;
     "file")
-	PACKAGES=$(dpkg -S $2 | cut -d':' -f1)
+	PACKAGES=$(dpkg -S $2 | cut -d':' -f1 | uniq)
 	for PACKAGE in $PACKAGES ; do
 	    do_search $PACKAGE
 	done
@@ -357,6 +451,9 @@ case $1 in
 	;;
     "repositories")
 	do_repositories
+	;;
+    "keep")
+	aptitude keep-all
 	;;
     "--author")
 	head -5 "`readlink -f "$0"`" | tail -2
