sbin: cleanup and unification

diff --git a/sbin/apt b/sbin/apt
--- a/sbin/apt
+++ b/sbin/apt
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
 # apt -- wrapper for aptitude/apt-*/dpkg*
-# Copyright (C) 2011  Alan "Shtark" SCHNEIDER
-#                     <shk.schneider[at]gmail.com>
+# Copyright (C) 2011-2012  Alan "Shtark" SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
@@ -11,8 +11,6 @@
 # bugs:
 #	wc -c counts special chars (with accents) twice
 #
-
-# v2.90
 
 set -f
 BINS="aptitude apt-get"
@@ -48,8 +46,7 @@ case $1 in
 esac
 
 # For full features, this script requiers:
-# dpkg + apt-cache + (aptitude | apt-get) + apt-show-versions + dpkg-query
-# Note that apt-get is mandatory for the source command
+# dpkg + apt-cache + apt-get + aptitude + apt-show-versions + dpkg-query
 [ -z "$APT" ] && for BIN in $BINS ; do [ -x "`which $BIN`" ] && APT=$BIN && break ; done
 
 #
@@ -57,33 +54,33 @@ esac
 #
 
 function usage() {
-    echo "Usage: `basename "$0"` [OPTION] COMMAND [PARAMS]" >&2
-    echo "     Options" >&2
-    echo "       -ap, --use-aptitude" >&2
-    echo "       -ag, --use-apt-get" >&2
-    echo "       -nr, --no-reverse" >&2
-    echo "     Commands" >&2
-    echo "       {--help|--version|--author}" >&2
-    echo "       update" >&2
-    echo "       upgrade" >&2
-    echo "       status <PACKAGE ...>" >&2
-    echo "       search <PACKAGE ...>" >&2
-    echo "       show <PACKAGE ...>" >&2
-    echo "       file <FILE>" >&2
-    echo "       install <PACKAGE ...>" >&2
-    echo "       reinstall <PACKAGE ...>" >&2
-    echo "       remove <PACKAGE ...>" >&2
-    echo "       purge <PACKAGE ...>" >&2
-    echo "       download <PACKAGE ...>" >&2
-    echo "       source <PACKAGE ...>" >&2
-    echo "       depends <PACKAGE ...>" >&2
-    echo "       hold [PACKAGE ...]" >&2
-    echo "       policy [PACKAGE ...]" >&2
-    echo "       size [LINES]" >&2
-    echo "       architecture" >&2
-    echo "       repositories" >&2
-    echo "       available" >&2
-    echo "       keep" >&2
+    echo "Usage: apt [OPTIONS] COMMAND [PARAMS]" >&2
+    echo "       Options" >&2
+    echo "         -ap, --use-aptitude" >&2
+    echo "         -ag, --use-apt-get" >&2
+    echo "         -nr, --no-reverse" >&2
+    echo "       Commands" >&2
+    echo "         {--help|--version|--author}" >&2
+    echo "         update" >&2
+    echo "         upgrade" >&2
+    echo "         status <PACKAGE ...>" >&2
+    echo "         search <PACKAGE ...>" >&2
+    echo "         show <PACKAGE ...>" >&2
+    echo "         file <FILE>" >&2
+    echo "         install <PACKAGE ...>" >&2
+    echo "         reinstall <PACKAGE ...>" >&2
+    echo "         remove <PACKAGE ...>" >&2
+    echo "         purge <PACKAGE ...>" >&2
+    echo "         download <PACKAGE ...>" >&2
+    echo "         source <PACKAGE ...>" >&2
+    echo "         depends <PACKAGE ...>" >&2
+    echo "         hold [PACKAGE ...]" >&2
+    echo "         policy [PACKAGE ...]" >&2
+    echo "         size [LINES]" >&2
+    echo "         architecture" >&2
+    echo "         repositories" >&2
+    echo "         available" >&2
+    echo "         keep" >&2
 }
 
 function do_status() {
@@ -157,7 +154,7 @@ function do_search() {
 function do_depends() {
     PACKAGE=$1
     check_package $PACKAGE
-    [ $? -ne 0 ] && echo "E: $PACKAGE: Package not found" >&2 && return
+    [ $? -ne 0 ] && echo "apt: package '$PACKAGE' not found" >&2 && return
     D=$(apt-cache depends -i $PACKAGE | sed '1d' | sed -r 's#\s+\w+: ##' | wc -l)
     case $REVERSE in
 	1)	echo -ne "\e[7m$PACKAGE\e[0m (\e[1m$D\e[0m) " ;;
@@ -190,7 +187,7 @@ function do_size() {
 
 function do_policy() {
     check_package $PACKAGE
-    [ $? -ne 0 ] && echo "E: $PACKAGE: Package not found" >&2 && return
+    [ $? -ne 0 ] && echo "apt: package '$PACKAGE' not found" >&2 && return
     while read LINE ; do
 	[ $REVERSE -eq 1 ] && echo -ne "\e[7m$PACKAGE\e[0m " || echo -n "$PACKAGE "
 	PRIOR=$(echo $LINE | cut -d' ' -f1)
@@ -244,7 +241,7 @@ function do_repositories() {
 
 function do_hold() {
     check_package $PACKAGE
-    [ $? -ne 0 ] && echo "E: $PACKAGE: Package not found" >&2 && return
+    [ $? -ne 0 ] && echo "apt: package '$PACKAGE' not found" >&2 && return
     IGNORE=$(dpkg --get-selections | grep hold)
     if [ -z "$IGNORE" ] ; then
 	echo "$PACKAGE hold" | dpkg --set-selections
@@ -284,66 +281,65 @@ function check_package() {
 
 case $1 in
     "update"|"upgrade")
-	[ `id -u` -ne 0 ] && echo "E: `id -un`: are you root?" >&2 && exit 1
-	[ $# -ne 1 ] && echo "E: Too many arguments" >&2 && usage && exit 1
+	[ `id -u` -ne 0 ] && echo "apt-$1: are you root, `id -un`?" >&2 && exit 1
+	[ $# -ne 1 ] && echo "apt-$1: too many arguments" >&2 && usage && exit 1
 	;;
     "install"|"reinstall"|"remove"|"purge"|"download"|"source")
-	[ `id -u` -ne 0 ] && echo "E: $1: Are you root, `id -un`?" >&2 && exit 1
-	[ $# -lt 2 ] && echo "E: $1: Too few arguments" >&2 && usage && exit 1
-	[ -z "$APT" ] && echo "E: $1: That command requiers `echo $BINS | sed 's/ / or /g'`" >&2 && exit 1
-	[ $1 = "source" -a $APT != "apt-get" ] && echo "E: $1: That Command requiers apt-get" >&2 && exit 1
+	[ `id -u` -ne 0 ] && echo "apt-$1: are you root, `id -un`?" >&2 && exit 1
+	[ $# -lt 2 ] && echo "apt-$1: too few arguments" >&2 && usage && exit 1
+	[ -z "$APT" ] && echo "apt-$1: that command requiers `echo $BINS | sed 's/ / or /g'`" >&2 && exit 1
+	[ $1 = "source" -a $APT != "apt-get" ] && echo "apt-$1: that command requiers apt-get" >&2 && exit 1
 	;;
     "status"|"search"|"show")
-	[ $1 != "status" -a ! -x "`which apt-cache`" ] && echo "E: $1: That command requiers apt-cache" >&2 && exit 1
-	[ $1 = "status" -a ! -x "`which apt-show-versions`" ] && echo "E: $1: That command requiers apt-show-versions" >&2 && exit 1
-	[ $# -lt 1 ] && echo "E: $1: Too few arguments" >&2 && usage && exit 1
+	[ $1 != "status" -a -z "`which apt-cache`" ] && echo "apt-$1: that command requiers apt-cache" >&2 && exit 1
+	[ $1 = "status" -a -z "`which apt-show-versions`" ] && echo "apt-$1: that command requiers apt-show-versions" >&2 && exit 1
+	[ $# -lt 1 ] && echo "apt-$1: too few arguments" >&2 && usage && exit 1
 	;;
     "file")
-	[ ! -x "`which apt-cache`" ] && echo "E: $1: That command requiers apt-cache" >&2 && exit 1
-	[ $# -lt 2 ] && echo "E: $1: Too few arguments" >&2 && usage && exit 1
-	[ $# -gt 2 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
-	[ ! -x "`which dpkg`" ] && echo "E: $1: That command requiers dpkg" >&2 && exit 1
-	[ ! -x "`which apt-cache`" ] && echo "E: $1: That command requiers apt-cache" >&2 && exit 1
+	[ -z "`which apt-cache`" ] && echo "apt-$1: that command requiers apt-cache" >&2 && exit 1
+	[ $# -lt 2 ] && echo "apt-$1: too few arguments" >&2 && usage && exit 1
+	[ $# -gt 2 ] && echo "apt-$1: too many arguments" >&2 && usage && exit 1
+	[ -z "`which dpkg`" ] && echo "apt-$1: that command requiers dpkg" >&2 && exit 1
+	[ -z "`which apt-cache`" ] && echo "apt-$1: that command requiers apt-cache" >&2 && exit 1
 	;;
     "depends")
-	[ ! -x "`which apt-cache`" ] && echo "E: $1: That command requiers apt-cache" >&2 && exit 1
-	[ $# -lt 2 ] && echo "E: $1: Too few arguments" >&2 && usage && exit 1
-	[ $# -gt 2 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
+	[ -z "`which apt-cache`" ] && echo "apt-$1: that command requiers apt-cache" >&2 && exit 1
+	[ $# -lt 2 ] && echo "apt-$1: too few arguments" >&2 && usage && exit 1
+	[ $# -gt 2 ] && echo "apt-$1: too many arguments" >&2 && usage && exit 1
 	;;
     "policy")
-	[ ! -x "`which apt-cache`" ] && echo "E: $1: That command requiers apt-cache" >&2 && exit 1
-	[ $# -lt 1 ] && echo "E: $1: Too few arguments" >&2 && usage && exit 1
+	[ -z "`which apt-cache`" ] && echo "apt-$1: that command requiers apt-cache" >&2 && exit 1
+	[ $# -lt 1 ] && echo "apt-$1: too few arguments" >&2 && usage && exit 1
 	;;
     "size")
-	[ ! -x "`which dpkg-query`" ] && echo "E: $1: That command requiers dpkg-query" >&2 && exit 1
-	[ $# -gt 2 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
-	[ -n "`echo "$2" | tr -d '[0-9]'`" ] && echo "E: $1: Not a number" >&2 && usage && exit 1
+	[ -z "`which dpkg-query`" ] && echo "apt-$1: that command requiers dpkg-query" >&2 && exit 1
+	[ $# -gt 2 ] && echo "apt-$1: too many arguments" >&2 && usage && exit 1
+	[ -n "`echo "$2" | tr -d '[0-9]'`" ] && echo "apt-$1: '$2' is not a number" >&2 && usage && exit 1
 	;;
     "architecture")
-	[ ! -x "`which dpkg`" ] && echo "E: $1: That command requiers dpkg" >&2 && exit 1
-	[ $# -gt 1 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
+	[ -z "`which dpkg`" ] && echo "apt-$1: that command requiers dpkg" >&2 && exit 1
+	[ $# -gt 1 ] && echo "apt-$1: too many arguments" >&2 && usage && exit 1
 	;;
     "available")
-	[ ! -x "`which apt-show-versions`" ] && echo "E: $1: That command requiers apt-show-versions" >&2 && exit 1
-	[ $# -gt 1 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
+	[ -z "`which apt-show-versions`" ] && echo "apt-$1: that command requiers apt-show-versions" >&2 && exit 1
+	[ $# -gt 1 ] && echo "apt-$1: too many arguments" >&2 && usage && exit 1
 	;;
     "keep")
-	[ $APT != "aptitude" ] && echo "E: $1: That command requiers aptitude" >&2 && exit 1
-	[ $# -gt 1 ] && echo "E: $1: Too many arguments" >&2 && usage && exit 1
+	[ $APT != "aptitude" ] && echo "apt-$1: that command requiers aptitude" >&2 && exit 1
+	[ $# -gt 1 ] && echo "apt-$1: too many arguments" >&2 && usage && exit 1
 	;;
     "repositories")
-	[ ! -x "`which dpkg`" ] && echo "E: $1: That command requiers dpkg" >&2 && exit 1
-	[ -z "`find /etc/apt -type f -name "*.list"`" ] && echo "E: $1: No .list file found in /etc/apt/" >&2 && exit 1
-	[ ! -e /var/lib/apt/lists ] && echo "E: $1: /var/lib/apt/lists not found" >&2 && exit 1
-	[ ! -d /var/lib/apt/lists ] && echo "E: $1: /var/lib/apt/lists not found" >&2 && exit 1
+	[ -z "`which dpkg`" ] && echo "apt-$1: that command requiers dpkg" >&2 && exit 1
+	[ -z "`find /etc/apt -type f -name "*.list"`" ] && echo "apt-$1: no .list file found in /etc/apt/" >&2 && exit 1
+	[ ! -e /var/lib/apt/lists ] && echo "apt-$1: /var/lib/apt/lists not found" >&2 && exit 1
+	[ ! -d /var/lib/apt/lists ] && echo "apt-$1: /var/lib/apt/lists not found" >&2 && exit 1
 	;;
     "hold")
-	[ ! -x "`which dpkg`" ] && echo "E: $1: That command requiers dpkg" >&2 && exit 1
+	[ -z "`which dpkg`" ] && echo "apt-$1: that command requiers dpkg" >&2 && exit 1
 	;;
-    "--help"|"--version"|"--author")
-	[ -z "`readlink -f "$0" | egrep '^/'`" ] && exit 1
+    "--help")
 	;;
-    *)	echo "E: $1: Unknown argument" >&2 && usage && exit 1 ;;
+    *)	echo "apt: unknown argument -- '$1'" >&2 && usage && exit 1 ;;
 esac
 
 #
@@ -379,7 +375,7 @@ case $1 in
 	    [ $N -gt 0 ] && echo ""
 	    N=$(($N + 1))
 	    check_package $PACKAGE
-	    [ $? -eq 0 ] && apt-cache show $PACKAGE 2>/dev/null | sed '/^$/d' || echo "E: $PACKAGE: Package not found" >&2
+	    [ $? -eq 0 ] && apt-cache show $PACKAGE 2>/dev/null | sed '/^$/d' || echo "apt: package '$PACKAGE' not found" >&2
 	done
 	;;
     "file")
@@ -452,12 +448,6 @@ case $1 in
 	;;
     "keep")
 	aptitude keep-all
-	;;
-    "--author")
-	head -5 "`readlink -f "$0"`" | tail -2
-	;;
-    "--version")
-	cat "`readlink -f "$0"`" | egrep '^#\s+v[0-9]' | sed -r 's/^#\s+//'
 	;;
     "--help")
 	usage
diff --git a/sbin/apt-add-ppa b/sbin/apt-add-ppa
--- a/sbin/apt-add-ppa
+++ b/sbin/apt-add-ppa
@@ -1,24 +1,24 @@
 #!/bin/bash
 #
 # apt-add-ppa -- recode for debian
-# Copyright (C) 2011  Alan "Shtark" SCHNEIDER
-#                     <shk.schneider[at]gmail.com>
+# Copyright (C) 2011-2012  Alan "Shtark" SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
 # under certain conditions.
 #
 
-[ `id -u` -ne 0 ] && echo "E: Permission denied. Are you root?" >&2 && exit 1
+[ `id -u` -ne 0 ] && echo "apt-add-ppa: are you root, `id -un`?" >&2 && exit 1
 
-if [ ! -x "`which lsb_release`" ] ; then
-    echo "E: lsb_release: Command not found" >&2
-    echo "   This most certainly means that this script ain't for your distro." >&2
+if [ -z "`which lsb_release`" ] ; then
+    echo "apt-add-ppa: command 'lsb_release' not found" >&2
+    echo "             This most certainly means that this script ain't for your distro." >&2
     exit 1
 fi
-[ ! -x "`which curl`" ] && echo "E: curl: Command not found" >&2 && exit 1
+[ -z "`which curl`" ] && echo "apt-add-ppa: command 'curl' not found" >&2 && exit 1
 
-[ $# -eq 0 ] && echo "Usage: `basename "$0"` <ppa> [...]" >&2 && exit 1
+[ $# -eq 0 ] && echo "Usage: apt-add-ppa <PPA [...]>" >&2 && exit 1
 
 LINUX_DISTRO=$(lsb_release -is)
 LINUX_CODENAME=$(lsb_release -cs)
@@ -31,7 +31,7 @@ case "$LINUX_DISTRO" in
 		LINUX_CODENAME="lucid"
 		;;
 	    *)
-		echo "E: Unsupported distro codename: $LINUX_CODENAME" >&2 && exit 1
+		echo "apt-add-ppa: unsupported distro codename '$LINUX_CODENAME'" >&2 && exit 1
 		;;
 	esac
 	;;
@@ -39,15 +39,15 @@ case "$LINUX_DISTRO" in
 	LINUX_DISTRO="ubuntu"
 	;;
     *)
-	echo "E: Unsupported distro: $LINUX_DISTRO" >&2 && exit 1
+	echo "apt-add-ppa: unsupported distro '$LINUX_DISTRO'" >&2 && exit 1
 	;;
 esac
 
 echo "Adding repositories as for $LINUX_DISTRO/$LINUX_CODENAME..."
 I=0
 for ARGV in $@ ; do
-    if [ "_`echo "$ARGV" | egrep '^ppa:[A-Za-z0-9]+/.+$'`" = "_" ] ; then
-	echo "E: Bad PPA: $ARGV" >&2
+    if [ -z "`echo "$ARGV" | egrep '^ppa:[A-Za-z0-9]+/.+$'`" ] ; then
+	echo "apt-add-ppa: bad PPA '$ARGV'" >&2
 	continue
     fi
     PPA=$(echo "$ARGV" | cut -d':' -f2)
@@ -55,13 +55,13 @@ for ARGV in $@ ; do
     REPO=$(echo "$ARGV" | cut -d':' -f2 | cut -d'/' -f2)
     echo " * $PPA"
     EXISTS=$(grep "deb http://ppa.launchpad.net/$PPA/" /etc/apt/sources.list)
-    [ "_$EXISTS" != "_" ] && echo "   E: Already exists: $PPA" >&2 && continue
-    echo " >> /etc/apt/sources.list
+    [ -n "$EXISTS" ] && echo "apt-add-ppa: ppa '$PPA' already exists" >&2 && continue
+    echo "" >> /etc/apt/sources.list
     echo "# apt-add-ppa: $PPA" >> /etc/apt/sources.list
     echo "deb http://ppa.launchpad.net/$PPA/$LINUX_DISTRO $LINUX_CODENAME main" >> /etc/apt/sources.list
     HTTP=$(curl -I "https://launchpad.net/~$USER" 2>/dev/null | head -1 | cut -d' ' -f2)
-    if [ "_$HTTP" = "_" ] || [ "_$HTTP" != "_200" ] ; then
-	echo "   E: No such PPA user: $USER" >&2
+    if [ -z "$HTTP" ] || [ "_$HTTP" != "_200" ] ; then
+	echo "apt-add-ppa: no such PPA user '$USER'" >&2
 	continue
     fi
     I=$(($I + 1))
diff --git a/sbin/apt-get-key b/sbin/apt-get-key
--- a/sbin/apt-get-key
+++ b/sbin/apt-get-key
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # apt-get-key -- auto-retrieve missing PUBKEY
-# Copyright (C) 2010-2011  Alan "Shtark" SCHNEIDER
+# Copyright (C) 2010-2012  Alan "Shtark" SCHNEIDER
 #                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
@@ -11,9 +11,9 @@
 
 SERVER="keyserver.ubuntu.com"
 
-[ `id -u` -ne 0 ] && echo "E: Permission denied. Are you root?" >&2 && exit 1
-[ ! -x "`which aptitude`" ] && echo "E: aptitude: Command not found" >&2 && exit 1
-[ ! -x "`which wget`" ] && echo "E: wget: Command not found" >&2 && exit 1
+[ `id -u` -ne 0 ] && echo "apt-get-key: are you root, `id -un`?" >&2 && exit 1
+[ -z "`which aptitude`" ] && echo "apt-get-key: command 'aptitude' not found" >&2 && exit 1
+[ -z "`which curl`" ] && echo "apt-get-key: command 'curl' not found" >&2 && exit 1
 
 chown -R `id -u`:`id -g` ~/.gnupg
 
@@ -21,7 +21,7 @@ function get_keycode() {
     SERVER=$1
     KEY=$2
     wget -q keyserver.ubuntu.com > /dev/null
-    [ $? -ne 0 ] && echo "E: $SERVER: Could not resolve host" >&2 && exit 1
+    [ $? -ne 0 ] && echo "apt-get-key: could not resolve host '$SERVER'" >&2 && exit 1
     gpg --keyserver $SERVER --recv-key $KEY 2>/dev/null >&2
     gpg -a --export $KEY | apt-key add - 2>/dev/null >&2
     # Error: 'ping: sendmsg: Operation not permitted' = firewall problem
@@ -50,4 +50,4 @@ else
     done
 fi
 
-echo "Done."
+echo "Done"
diff --git a/sbin/apt-ping b/sbin/apt-ping
--- a/sbin/apt-ping
+++ b/sbin/apt-ping
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # apt-ping -- ping your apt repositories
-# Copyright (C) 2010-2011  Alan "Shtark" SCHNEIDER
+# Copyright (C) 2010-2012  Alan "Shtark" SCHNEIDER
 #                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
@@ -12,8 +12,8 @@
 OK=$(echo -e "[ \033[0;32mok\033[0;0m ]")
 KO=$(echo -e "[ \033[0;31mko\033[0;0m ]")
 
-[ -z "`cat /proc/net/arp | egrep '^[0-9]'`" ] && echo "E: `basename "$0"`: No network connection" >&2 && exit 1
-[ ! -x "`which curl`" ] && echo "E: curl: Command not found" >&2 && exit 1
+[ -z "`cat /proc/net/arp | egrep '^[0-9]'`" ] && echo "apt-ping: no network connection" >&2 && exit 1
+[ -z "`which curl`" ] && echo "apt-ping: command 'curl' not found" >&2 && exit 1
 
 function ping_apt() {
     HTTP_STATUS=$(curl -I "$URL" 2>/dev/null | grep -E '^HTTP' | tr -d "\r" | awk '{print "HTTP/"$2}')
@@ -28,7 +28,6 @@ function ping_apt() {
 	[ "$LOCATION" = "$URL" ] && echo "!!!!!"
 	if [ -n "$LOCATION" ] ; then
 	    HTTP_STATUS=$(curl -I "$LOCATION" 2>/dev/null | grep -E '^HTTP' | tr -d "\r" | awk '{print "HTTP/"$2}')
-	    #URL=$(echo $LOCATION | cut -d' ' -f3- | cut -d'/' -f1,2,3)
 	    ping_apt "$FILE" "$LINE" "$LOCATION"
 	fi
     else
@@ -41,9 +40,9 @@ function ping_apt() {
 if [ $# -ne 0 ] ; then
     FILE=$(readlink -f "$1")
     echo " * Reading $FILE..."
-    [ ! -e "$FILE" ] && echo "E: $FILE: No such file or directory" >&2 && continue
-    [ -d "$FILE" ] && echo "E: $FILE: Is a directory" >&2 && continue
-    [ ! -r "$FILE" ] && echo "E: $FILE: Permission denied" >&2 && continue
+    [ ! -e "$FILE" ] && echo "apt-ping: $FILE: no such file or directory" >&2 && continue
+    [ -d "$FILE" ] && echo "apt-ping: $FILE: is a directory" >&2 && continue
+    [ ! -r "$FILE" ] && echo "apt-ping: $FILE: permission denied" >&2 && continue
     grep -HEn '^deb' $FILE 2>/dev/null | sed -e 's/:deb//g' -e 's/:/ /' | awk '{print $1" "$2" " $3}' | \
 	while read REPOSITORY ; do
 	    LINE=$(echo $REPOSITORY | cut -d' ' -f2)
@@ -51,15 +50,14 @@ if [ $# -ne 0 ] ; then
 	    ping_apt "$FILE" "$LINE" "$URL"
         done
 else
-    find /etc/apt -type f -name "*.list" | \
-	while read FILE ; do
-	    echo " * Reading $FILE..."
-	    [ ! -r "$FILE" ] && echo "E: $FILE: Permission denied" >&2 && continue
-	    grep -HEn '^deb' $FILE 2>/dev/null | sed -e 's/:deb//g' -e 's/:/ /' | awk '{print $1" "$2" " $3}' | \
-		while read REPOSITORY ; do
-		    LINE=$(echo $REPOSITORY | cut -d' ' -f2)
-		    URL=$(echo $REPOSITORY | cut -d' ' -f3- | cut -d'/' -f1,2,3)
-		    ping_apt "$FILE" "$LINE" "$URL"
-                done
-           done
+    while read FILE ; do
+	echo " * Reading $FILE..."
+	[ ! -r "$FILE" ] && echo "apt-ping: $FILE: permission denied" >&2 && continue
+	grep -HEn '^deb' $FILE 2>/dev/null | sed -e 's/:deb//g' -e 's/:/ /' | awk '{print $1" "$2" " $3}' | \
+	    while read REPOSITORY ; do
+	    LINE=$(echo $REPOSITORY | cut -d' ' -f2)
+	    URL=$(echo $REPOSITORY | cut -d' ' -f3- | cut -d'/' -f1,2,3)
+	    ping_apt "$FILE" "$LINE" "$URL"
+        done
+    done < <(find /etc/apt -type f -name "*.list")
 fi
diff --git a/sbin/network b/sbin/network
--- a/sbin/network
+++ b/sbin/network
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # network -- manage ethernet and wireless connections easily from the command line
-# Copyright (C) 2010-2011  Alan "Shtark" SCHNEIDER
+# Copyright (C) 2010-2012  Alan "Shtark" SCHNEIDER
 #                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
@@ -9,26 +9,25 @@
 # under certain conditions.
 #
 
-[ `id -u` -ne 0 ] && echo "E: Permission denied. Are you root?" >&2 && exit 1
+[ `id -u` -ne 0 ] && echo "network: are you root, `id -un`?" >&2 && exit 1
 
-[ -z "`which ifconfig`" ] && echo "E: ifconfig: Command not found" >&2 && exit 1
-[ -z "`which iwlist`" ] && echo "E: iwlist: Command not found" >&2 && exit 1
-[ -z "`which iwconfig`" ] && echo "E: iwconfig: Command not found" >&2 && exit 1
-[ -z "`which dhclient`" ] && echo "E: dhclient: Command not found" >&2 && exit 1
-
-VERSION="3.2"
+[ -z "`which ifconfig`" ] && echo "network: command 'ifconfig' not found" >&2 && exit 1
+[ -z "`which iwlist`" ] && echo "network: command 'iwlist' not found" >&2 && exit 1
+[ -z "`which iwconfig`" ] && echo "network: command 'iwconfig' not found" >&2 && exit 1
+[ -z "`which dhclient`" ] && echo "network: command 'dhclient' not found" >&2 && exit 1
 
 # Usage
 
 function usage() {
-    echo "Usage: `basename "$0"` devices                        list devices" >&2
-    echo "       `basename "$0"` [eth|wlan|usb] list [up|down]  list interfaces" >&2
-    echo "       `basename "$0"` [eth|wlan|usb] status          interfaces status" >&2
-    echo "       `basename "$0"` <interface> up                 enable interface" >&2
-    echo "       `basename "$0"` <interface> down               disable interface" >&2
-    echo "       `basename "$0"` <interface> status             interface status" >&2
-    echo "       `basename "$0"` <wlan> ssid                    list SSID for interface" >&2
-    echo "       `basename "$0"` <wlan> connect <ssid> [key]    connect to SSID throught interface" >&2
+    echo "Usage: network devices                        list devices" >&2
+    echo "               [eth|wlan|usb] list [up|down]  list interfaces" >&2
+    echo "               [eth|wlan|usb] status          interfaces status" >&2
+    echo "               <interface> up                 enable interface" >&2
+    echo "               <interface> down               disable interface" >&2
+    echo "               <interface> status             interface status" >&2
+    echo "               <wlan> ssid                    list SSID for interface" >&2
+    echo "               <wlan> connect <ssid> [key]    connect to SSID throught interface" >&2
+    echo "               --help" >&2
     exit 1
 }
 
@@ -121,34 +120,34 @@ function type_status() {
 # Interface-specific
 
 function interface_up() {
-    [ `exists $1` = "no" ] && echo "$1: No such interface" >&2 && return
-    [ `getStatus $1` = "down" ] && echo "$1: Enabling..." && ifconfig $1 up || echo "$1: Interface is already UP"
+    [ `exists $1` = "no" ] && echo "$1: no such interface" >&2 && return
+    [ `getStatus $1` = "down" ] && echo "$1: enabling..." && ifconfig $1 up || echo "$1: interface is already UP"
 }
 
 function interface_down() {
-    [ `exists $1` = "no" ] && echo "$1: No such interface" >&2 && return
-    [ `getStatus $1` = "up" ] && echo "$1: Disabling..." && ifconfig $1 down || echo "$1: Interface is already DOWN"
+    [ `exists $1` = "no" ] && echo "$1: no such interface" >&2 && return
+    [ `getStatus $1` = "up" ] && echo "$1: disabling..." && ifconfig $1 down || echo "$1: interface is already DOWN"
 }
 
 function interface_status() {
-    [ `exists $1` = "no" ] && echo "$1: No such interface" >&2 && return
+    [ `exists $1` = "no" ] && echo "$1: no such interface" >&2 && return
     [ `getStatus $1` = "up" ] && echo "$1: UP "$(getIp $1) || echo "$1: DOWN"
 }
 
 # Wireless specific
 
 function wlan_ssid() {
-    [ `exists $1` = "no" ] && echo "$1: No such interface" >&2 && return
-    [ `getStatus $1` = "down" ] && echo "$1: Interface is DOWN" && return
+    [ `exists $1` = "no" ] && echo "$1: no such interface" >&2 && return
+    [ `getStatus $1` = "down" ] && echo "$1: interface is DOWN" && return
     iwlist $1 scan | egrep '^ *ESSID' | sed -r 's/^\s+//' | grep -v 'ESSID:"' | cut -d'"' -f2
 }
 
 function wlan_connect() {
-    [ `exists $1` = "no" ] && echo "$1: No such interface" >&2 && return
-    [ `getStatus $1` = "down" ] && echo "$1: Interface is DOWN" && return
-    echo "$1: Connecting to \`$2'..."
+    [ `exists $1` = "no" ] && echo "$1: no such interface" >&2 && return
+    [ `getStatus $1` = "down" ] && echo "$1: interface is DOWN" && return
+    echo "$1: connecting to '$2'..."
     iwconfig $1 essid "$2" key "s:$3"
-    echo "$1: Obtaining IP address from \`$2'..."
+    echo "$1: obtaining IP address from '$2'..."
     dhclient $1
     status_single $1
 }
@@ -158,13 +157,10 @@ function wlan_connect() {
 [ $# -eq 0 ] && usage
 case "$1" in
     --help)
-	[ $# -gt 1 ] && echo "E: Unexpected argument: \`$2'" >&2 && exit
+	[ $# -gt 1 ] && echo "network: unexpected argument '$2'" >&2 && exit
 	usage ;;
-    --version)
-	[ $# -gt 1 ] && echo "E: Unexpected argument: \`$2'" >&2 && exit
-	echo $(basename "$0")" v$VERSION ("$(uname -o)" "$(uname -r)")" ;;
     devices)
-	[ $# -gt 1 ] && echo "E: Unexpected argument: \`$2'" >&2 && exit
+	[ $# -gt 1 ] && echo "network: unexpected argument '$2'" >&2 && exit
 	devices ;;
     eth|wlan|usb)
 	case "$2" in
@@ -172,59 +168,59 @@ case "$1" in
 		if [ $# -eq 2 ] ; then
 		    type_list $1
 		else
-		    [ $# -gt 3 ] && echo "E: Unexpected argument: \`$4'" >&2 && exit
+		    [ $# -gt 3 ] && echo "network: unexpected argument '$4'" >&2 && exit
 		    case "$3" in
 			up) type_list_up $1 ;;
 			down) type_list_down $1 ;;
-			*) echo "E: Unrecognized argument: \`$3'" >&2 && exit 1 ;;
+			*) echo "network: unrecognized argument '$3'" >&2 && exit 1 ;;
 		    esac
 		fi
 		;;
 	    status)
-		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
+		[ $# -gt 2 ] && echo "network: unexpected argument '$3'" >&2 && exit
 		type_status $1 ;;
-	    *) echo "E: Unrecognized argument: \`$2'" >&2 && exit 1 ;;
+	    *) echo "network: unrecognized argument '$2'" >&2 && exit 1 ;;
 	esac ;;
     list)
 	if [ $# -eq 1 ] ; then
 	    interfaces_list
 	else
-	    [ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
+	    [ $# -gt 2 ] && echo "network: unexpected argument '$3'" >&2 && exit
 	    case "$2" in
 		up) interfaces_list_up ;;
 		down) interfaces_list_down ;;
-		*) echo "E: Unrecognized argument: \`$2'" >&2 && exit 1 ;;
+		*) echo "network: unrecognized argument '$2'" >&2 && exit 1 ;;
 	    esac
 	fi ;;
     status)
-	[ $# -gt 1 ] && echo "E: Unexpected argument: \`$2'" >&2 && exit
+	[ $# -gt 1 ] && echo "network: unexpected argument '$2'" >&2 && exit
 	interfaces_status ;;
     eth[0-9]|usb[0])
-	[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
+	[ $# -gt 2 ] && echo "network: unexpected argument '$3'" >&2 && exit
 	case "$2" in
 	    up) interface_up "$1" ;;
 	    down) interface_down "$1" ;;
 	    status) interface_status "$1" ;;
-	    *) echo "E: Unrecognized argument: \`$2'" >&2 && exit 1 ;;
+	    *) echo "network: unrecognized argument '$2'" >&2 && exit 1 ;;
 	esac ;;
     wlan[0-9])
-	[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
+	[ $# -gt 2 ] && echo "network: unexpected argument '$3'" >&2 && exit
 	case "$2" in
 	    up) interface_up "$1" ;;
 	    down)
-		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
+		[ $# -gt 2 ] && echo "network: unexpected argument '$3'" >&2 && exit
 		interface_down "$1" ;;
 	    status)
-		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
+		[ $# -gt 2 ] && echo "network: unexpected argument '$3'" >&2 && exit
 		interface_status "$1" ;;
 	    ssid)
-		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
+		[ $# -gt 2 ] && echo "network: unexpected argument '$3'" >&2 && exit
 		wlan_ssid "$1" ;;
 	    connect)
-		[ $# -eq 2 ] && echo "E: Missing argument: <ssid>" >&2 && exit 1
-		[ $# -gt 4 ] && echo "E: Unexpected argument: \`$5'" >&2 && exit
+		[ $# -eq 2 ] && echo "network: missing argument <ssid>" >&2 && exit 1
+		[ $# -gt 4 ] && echo "network: unexpected argument '$5'" >&2 && exit
 		wlan_connect "$1" "$2" "$3" ;;
-	    *) echo "E: Unrecognized argument: \`$2'" >&2 && exit 1 ;;
+	    *) echo "network: unrecognized argument '$2'" >&2 && exit 1 ;;
 	esac ;;
-    *) echo "E: Unrecognized argument: \`$1'" >&2 && exit 1 ;;
+    *) echo "network: unrecognized argument '$1'" >&2 && exit 1 ;;
 esac
diff --git a/sbin/no-space-left-on-device b/sbin/no-space-left-on-device
--- a/sbin/no-space-left-on-device
+++ b/sbin/no-space-left-on-device
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
 # no-space-left-on-device -- cleanup some space
-# Copyright (C) 2011  Alan "Shtark" SCHNEIDER
-#                     <shk.schneider[at]gmail.com>
+# Copyright (C) 2011-2012  Alan "Shtark" SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
@@ -13,9 +13,9 @@ echo " * Actual situation"
 
 df -h /
 
-[ `id -u` -ne 0 ] && echo "E: Permission denied. Are you root?" >&2 && exit 1
-[ -z "`which dpkg`" ] && echo "E: dpkg: Command not found" >&2 && exit 1
-[ -z "`which aptitude`" ] && echo "E: aptitude: Command not found" >&2 && exit 1
+[ `id -u` -ne 0 ] && echo "no-space-left-on-device: are you root, `id -un`?" >&2 && exit 1
+[ -z "`which dpkg`" ] && echo "no-space-left-on-device: command 'dpkg' not found" >&2 && exit 1
+[ -z "`which aptitude`" ] && echo "no-space-left-on-device: command 'aptitude' not found" >&2 && exit 1
 
 echo " * Cleaning..."
 
@@ -40,4 +40,4 @@ find /home/*/.thumbnails -type f -atime +7 -exec rm {} \;
 echo "   localepurge"
 [ -z "`which localepurge`" ] && aptitude install localepurge || dpkg-reconfigure localepurge
 
-echo "Done."
+echo "Done"
diff --git a/sbin/power_off b/sbin/power_off
--- a/sbin/power_off
+++ b/sbin/power_off
@@ -1,18 +1,18 @@
 #!/bin/bash
 #
 # power_off -- set a timer to shutdown
-# Copyright (C) 2011  Alan "Shtark" SCHNEIDER
-#                     <shk.schneider[at]gmail.com>
+# Copyright (C) 2011-2012  Alan "Shtark" SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
 # under certain conditions.
 #
 
-[ ! -x "`which shutdown`" ] && echo "E: shutdown: Command not found" >&2 && exit 1
+[ -z "`which shutdown`" ] && echo "power_off: command 'shutdown' not found" >&2 && exit 1
 
 function usage() {
-    echo "Usage: `basename "$0"` <TIME>" >&2
+    echo "Usage: power_off <TIME>" >&2
     echo "       TIME can have a format dd:hh:mm, hh:mm, mm" >&2
     exit 1
 }
diff --git a/sbin/whatismyip b/sbin/whatismyip
--- a/sbin/whatismyip
+++ b/sbin/whatismyip
@@ -1,19 +1,19 @@
 #!/bin/bash
 #
 # whatismyip -- retrieve your internal/external IP from command line
-# Copyright (C) 2010  Alan "Shtark" SCHNEIDER
-#                     <shk.schneider[at]gmail.com>
+# Copyright (C) 2010-2012  Alan "Shtark" SCHNEIDER
+#                          <shk.schneider[at]gmail.com>
 #
 # This program comes with ABSOLUTELY NO WARRANTY.
 # This is free software, and you are welcome to redistribute it
 # under certain conditions.
 #
 
-[ "_`which ifconfig`" = "_" ] && echo "E: ifconfig: Command not found." >&2 && exit 1
-[ "_`which wget`" = "_" ] && echo "E: wget: Command not found." >&2 && exit 1
+[ -z "`which ifconfig`" ] && echo "whatismyip: command 'ifconfig' not found" >&2 && exit 1
+[ -z "`which curl`" ] && echo "whatismyip: command 'curl' not found" >&2 && exit 1
 
 INTERNAL=$(ifconfig  | grep "inet addr:" | grep Bcast | awk '{print $2}' | cut -d':' -f2)
-EXTERNAL=$(curl ifconfig.me/ip)
+EXTERNAL=$(curl -s ifconfig.me/ip)
 echo "$INTERNAL $EXTERNAL"
 
 # Todo: retrieve interface
