Updated '-z' tests Light network + usb support Fixed ping-apt with HTTP/302 redirects Use /proc/net/arp to get internal ip address in whatismyip Fixed lastlogin

diff --git a/root_only/apt-add-ppa b/root_only/apt-add-ppa
--- a/root_only/apt-add-ppa
+++ b/root_only/apt-add-ppa
@@ -1,17 +1,18 @@
 #!/bin/bash
 #
 # This script should be placed in /usr/sbin/
-# chown root:root /usr/sbin/add-apt-repository
-# chmod 755 /usr/sbin/add-apt-repository
+# chown root:root /usr/sbin/apt-add-ppa
+# chmod 755 /usr/sbin/apt-add-ppa
 #
 
 [ `whoami` != "root" ] && echo "E: Permission denied. Are you root?" >&2 && exit 1
-if [ "_`which lsb_release`" = "_" ] ; then
+
+if [ -z "`which lsb_release`" ] ; then
     echo "E: lsb_release: Command not found" >&2
     echo "   This most certainly means that this script ain't for your distro." >&2
     exit 1
 fi
-[ "_`which curl`" = "_" ] && echo "E: curl: Command not found" >&2 && exit 1
+[ -z "`which curl`" ] && echo "E: curl: Command not found" >&2 && exit 1
 
 [ $# -eq 0 ] && echo "Usage: `basename $0` <ppa> [...]" >&2 && exit 1
 
@@ -38,10 +39,6 @@ case "$LINUX_DISTRO" in
 	;;
 esac
 
-#
-# Add PPA
-#
-
 echo "Adding repositories as for $LINUX_DISTRO/$LINUX_CODENAME..."
 I=0
 for ARGV in $@ ; do
@@ -56,7 +53,7 @@ for ARGV in $@ ; do
     EXISTS=$(grep "deb http://ppa.launchpad.net/$PPA/" /etc/apt/sources.list)
     [ "_$EXISTS" != "_" ] && echo "   E: Already exists: $PPA" >&2 && continue
     echo "" >> /etc/apt/sources.list
-    echo "# add-apt-repository: $PPA" >> /etc/apt/sources.list
+    echo "# apt-add-ppa: $PPA" >> /etc/apt/sources.list
     echo "deb http://ppa.launchpad.net/$PPA/$LINUX_DISTRO $LINUX_CODENAME main" >> /etc/apt/sources.list
     HTTP=$(curl -I "https://launchpad.net/~$USER" 2>/dev/null | head -1 | cut -d' ' -f2)
     if [ "_$HTTP" = "_" ] || [ "_$HTTP" != "_200" ] ; then
@@ -68,28 +65,5 @@ done
 echo -n "Added $I repositor"
 [ $I -gt 1 ] && echo -n "ies" || echo -n "y"
 echo " to /etc/apt/sources.list"
-
-#
-# Get GPG
-#
-
-echo " * Running aptitude update..."
-ERRORS=$(aptitude update 2>&1 | grep "W: GPG error:" | awk '{print $NF}')
-E=0
-for ERROR in $ERRORS ; do
-    E=$(($E + 1))
-done
-echo "   $E GPG error(s) found"
-[ $E -eq 0 ] && exit 0
-SERVER="keyserver.ubuntu.com"
-echo " * Resolving with <$SERVER>..."
-for ERROR in $ERRORS ; do
-    KEY=$(echo $ERROR | rev | cut -c 1-8 | rev)
-    echo "   GPG error: "$ERROR" -> keycode: "$KEY
-    gpg --keyserver $SERVER --recv-key $KEY 2>/dev/null >&2
-    gpg -a --export $KEY | apt-key add - 2>/dev/null >&2
-done
-
-echo "Done."
 
 exit 0
diff --git a/root_only/network b/root_only/network
--- a/root_only/network
+++ b/root_only/network
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# network - manage ethernet and wireless connections easily from the command line
+# network v3.2 - manage ethernet and wireless connections easily from the command line
 # Copyright (C) 2010  Alan "Shtark" SCHNEIDER
 #                     <shk.schneider[at]gmail.com>
 #
@@ -11,234 +11,147 @@
 
 [ `whoami` != "root" ] && echo "E: Permission denied. Are you root?" >&2 && exit 1
 
-[ "_`which ifconfig`" = "_" ] && echo "E: ifconfig: Command not found." >&2 && exit 1
-#[ "_`which iwlist`" = "_" ] && echo "E: iwlist: Command not found." >&2 && exit 1
-#[ "_`which iwconfig`" = "_" ] && echo "E: iwconfig: Command not found." >&2 && exit 1
-[ "_`which dhclient`" = "_" ] && echo "E: dhclient: Command not found." >&2 && exit 1
+[ -z "`which ifconfig`" ] && echo "E: ifconfig: Command not found." >&2 && exit 1
+[ -z "`which iwlist`" ] && echo "E: iwlist: Command not found." >&2 && exit 1
+[ -z "`which iwconfig`" ] && echo "E: iwconfig: Command not found." >&2 && exit 1
+[ -z "`which dhclient`" ] && echo "E: dhclient: Command not found." >&2 && exit 1
+
+VERSION="3.2"
 
 # Usage
 
 function usage() {
     echo "Usage:" >&2
-    echo "       `basename $0` devices                      list devices" >&2
-    echo "       `basename $0` [eth|wlan] list [up|down]    list interfaces" >&2
-    echo "       `basename $0` [eth|wlan] status            interfaces status" >&2
-    echo "       `basename $0` <interface> up               enable interface" >&2
-    echo "       `basename $0` <interface> down             disable interface" >&2
-    echo "       `basename $0` <interface> status           interface status" >&2
-    echo "       `basename $0` <wlan> ssid                  list SSID for interface" >&2
-    echo "       `basename $0` <wlan> connect <ssid> [key]  connect to SSID throught interface" >&2
+    echo "       `basename $0` devices                        list devices" >&2
+    echo "       `basename $0` [eth|wlan|usb] list [up|down]  list interfaces" >&2
+    echo "       `basename $0` [eth|wlan|usb] status          interfaces status" >&2
+    echo "       `basename $0` <interface> up                 enable interface" >&2
+    echo "       `basename $0` <interface> down               disable interface" >&2
+    echo "       `basename $0` <interface> status             interface status" >&2
+    echo "       `basename $0` <wlan> ssid                    list SSID for interface" >&2
+    echo "       `basename $0` <wlan> connect <ssid> [key]    connect to SSID throught interface" >&2
     exit 1
 }
 
 # Utility
 
-function interface_exists() {
-    # 1: interface
-    [ "_`ifconfig -a -s | egrep "^$1"`" = "_" ] && echo "no" || echo "yes"
+function exists() {
+    [ -z "`ifconfig -a -s | egrep "^$1"`" ] && echo "no" || echo "yes"
 }
 
-function interface_status() {
-    # 1: interface
-    [ "_`ifconfig -s | egrep "^$1"`" = "_" ] && echo "down" || echo "up"
+function getStatus() {
+    [ -z "`ifconfig -s | egrep "^$1"`" ] && echo "down" || echo "up"
 }
 
-function interface_type() {
-    # 1: interfaca
-    [ "_`echo $1 | egrep '^eth'`" = "_" ] && echo "wlan" || echo "eth"
+function getType() {
+    case $1 in
+	eth*) echo "eth" ;;
+	wlan*) echo "wlan" ;;
+	usb*) echo "usb" ;;
+    esac
 }
 
 function getIp() {
-    # 1: interface
     echo $(ifconfig $1 | grep 'inet addr' | cut -d':' -f2 | cut -d' ' -f1)
 }
-
-# Devices
 
 function devices() {
     lspci -nn | egrep -i '(ethernet|wlan|wireless|wifi)' | cut -d' ' -f2- | sed -r 's/ \[[0-9a-fA-F:]+\]//g' | uniq
 }
 
-# List
+# Interfaces
 
-function list() {
-    ifconfig -a -s | egrep '^(eth|wlan)' | awk '{print $1}'
+function interfaces_list() {
+    ifconfig -a -s | egrep '^(eth|wlan|usb)' | awk '{print $1}'
 }
 
-function list_up() {
-    ifconfig -s | egrep '^(eth|wlan)' | awk '{print $1}'
+function interfaces_list_up() {
+    ifconfig -s | egrep '^(eth|wlan|usb)' | awk '{print $1}'
 }
 
-function list_down() {
-    INTERFACES=$(ifconfig -a -s | egrep '^(eth|wlan)' | awk '{print $1}')
-    [ "_$INTERFACES" = "_" ] && return
+function interfaces_list_down() {
+    INTERFACES=$(ifconfig -a -s | egrep '^(eth|wlan|usb)' | awk '{print $1}')
+    [ -z "$INTERFACES" ] && return
     for INTERFACE in $INTERFACES ; do
-	if [ `interface_status $INTERFACE` = "down" ] ; then
-	    echo "$INTERFACE"
-	fi
+	[ `getStatus $INTERFACE` = "down" ] && echo "$INTERFACE"
     done
 }
 
-# Status
-
-function status() {
-    INTERFACES=$(ifconfig -a -s | egrep '^(eth|wlan)' | awk '{print $1}')
-    [ "_$INTERFACES" = "_" ] && return
+function interfaces_status() {
+    INTERFACES=$(ifconfig -a -s | egrep '^(eth|wlan|usb)' | awk '{print $1}')
+    [ -z "$INTERFACES" ] && return
     for INTERFACE in $INTERFACES ; do
-	if [ `interface_status $INTERFACE` = "up" ] ; then
-	    echo "$INTERFACE: UP "$(getIp $INTERFACE)
-	else
-	    echo "$INTERFACE: DOWN"
-	fi
+	[ `getStatus $INTERFACE` = "up" ] && echo "$INTERFACE: UP "$(getIp $INTERFACE) || echo "$INTERFACE: DOWN"
     done
 }
 
-# Ethernet
+# Type-specific
 
-function eth_list() {
-    INTERFACES=$(ifconfig -a -s | egrep '^eth' | awk '{print $1}')
-    [ "_$INTERFACES" = "_" ] && return
+function type_list() {
+    INTERFACES=$(ifconfig -a -s | egrep "^$1" | awk '{print $1}')
+    [ -z "$INTERFACES" ] && return
     for INTERFACE in $INTERFACES ; do
-	if [ `interface_type $INTERFACE` = "eth" ] ; then
-	    echo "$INTERFACE"
-	fi
+	[ `getType $INTERFACE` = "$1" ] && echo "$INTERFACE"
     done
 }
 
-function eth_list_up() {
-    INTERFACES=$(ifconfig -s | egrep '^eth' | awk '{print $1}')
-    [ "_$INTERFACES" = "_" ] && return
+function type_list_up() {
+    INTERFACES=$(ifconfig -s | egrep "^$1" | awk '{print $1}')
+    [ -z "$INTERFACES" ] && return
     for INTERFACE in $INTERFACES ; do
-	if [ `interface_type $INTERFACE` = "eth" ] ; then
-	    echo "$INTERFACE"
-	fi
+	[ `getType $INTERFACE` = "$1" ] && [ `getStatus $INTERFACE` = "up" ] && echo "$INTERFACE"
     done
 }
 
-function eth_list_down() {
-    INTERFACES=$(ifconfig -a -s | egrep '^eth' | awk '{print $1}')
-    [ "_$INTERFACES" = "_" ] && return
+function type_list_down() {
+    INTERFACES=$(ifconfig -a -s | egrep "^$1" | awk '{print $1}')
+    [ -z "$INTERFACES" ] && return
     for INTERFACE in $INTERFACES ; do
-	if [ `interface_type $INTERFACE` = "eth" ] && [ `interface_status $INTERFACE` = "down" ] ; then
-	    echo "$INTERFACE"
-	fi
+	[ `getType $INTERFACE` = "$1" ] && [ `getStatus $INTERFACE` = "down" ] && echo "$INTERFACE"
     done
 }
 
-function eth_up() {
-    # 1: interface
-    [ `interface_exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
-    if [ `interface_status $1` = "down" ] ; then
-	echo "$1: Enabling..."
-	ifconfig $1 up
-    else
-	echo "$1: Interface is already UP."
-    fi
-}
-
-function eth_down() {
-    # 1: interface
-    [ `interface_exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
-    if [ `interface_status $1` = "up" ] ; then
-	echo "$1: Disabling..."
-	ifconfig $1 down
-    else
-	echo "$1: Interface is already DOWN."
-    fi
-}
-
-function eth_status() {
-    # 1: interface
-    [ `interface_exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
-    if [ `interface_status $1` = "up" ] ; then
-	echo "$1: UP "$(getIp $1)
-    else
-	echo "$1: DOWN"
-    fi
-}
-
-# Wireless
-
-function wlan_list() {
-    INTERFACES=$(ifconfig -a -s | egrep '^wlan' | awk '{print $1}')
-    [ "_$INTERFACES" = "_" ] && return
+function type_status() {
+    INTERFACES=$(ifconfig -a -s | egrep "^$1" | awk '{print $1}')
+    [ -z "$INTERFACES" ] && return
     for INTERFACE in $INTERFACES ; do
-	if [ `interface_type $INTERFACE` = "wlan" ] ; then
-	    echo "$INTERFACE"
-	fi
+	[ `getStatus $INTERFACE` = "up" ] && echo "$INTERFACE: UP "$(getIp $INTERFACE) || echo "$INTERFACE: DOWN"
     done
 }
 
-function wlan_list_up() {
-    INTERFACES=$(ifconfig -s | egrep '^wlan' | awk '{print $1}')
-    [ "_$INTERFACES" = "_" ] && return
-    for INTERFACE in $INTERFACES ; do
-	if [ `interface_type $INTERFACE` = "wlan" ] ; then
-	    echo "$INTERFACE"
-	fi
-    done
+# Interface-specific
+
+function interface_up() {
+    [ `exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
+    [ `getStatus $1` = "down" ] && echo "$1: Enabling..." && ifconfig $1 up || echo "$1: Interface is already UP."
 }
 
-function wlan_list_down() {
-    INTERFACES=$(ifconfig -a -s | egrep '^wlan' | awk '{print $1}')
-    [ "_$INTERFACES" = "_" ] && return
-    for INTERFACE in $INTERFACES ; do
-	if [ `interface_type $INTERFACE` = "wlan" ] && [ `interface_status $INTERFACE` = "down" ] ; then
-	    echo "$INTERFACE"
-	fi
-    done
+function interface_down() {
+    [ `exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
+    [ `getStatus $1` = "up" ] && echo "$1: Disabling..." && ifconfig $1 down || echo "$1: Interface is already DOWN."
 }
 
-function wlan_up() {
-    # 1: interface
-    [ `interface_exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
-    if [ `interface_status $1` = "down" ] ; then
-	echo "$1: Enabling..."
-	ifconfig $1 up
-    else
-	echo "$1: Interface is already UP."
-    fi
+function interface_status() {
+    [ `exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
+    [ `getStatus $1` = "up" ] && echo "$1: UP "$(getIp $1) || echo "$1: DOWN"
 }
 
-function wlan_down() {
-    # 1: interface
-    [ `interface_exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
-    if [ `interface_status $1` = "up" ] ; then
-	echo "$1: Disabling..."
-	ifconfig $1 down
-    else
-	echo "$1: Interface is already DOWN."
-    fi
-}
-
-function wlan_status() {
-    # 1: interface
-    [ `interface_exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
-    if [ `interface_status $1` = "up" ] ; then
-	echo "$1: UP "$(getIp $1)
-    else
-	echo "$1: DOWN"
-    fi
-}
+# Wireless specific
 
 function wlan_ssid() {
-    # 1: interface
-    [ `interface_exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
-    [ `interface_status $1` = "down" ] && echo "$1: Interface is DOWN." && return
-    iwlist $1 scan | egrep '^ESSID' | cut -d'"' -f2
+    [ `exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
+    [ `getStatus $1` = "down" ] && echo "$1: Interface is DOWN." && return
+    iwlist $1 scan | egrep '^ *ESSID' | sed -r 's/^\s+//' | grep -v 'ESSID:""' | cut -d'"' -f2
 }
 
 function wlan_connect() {
-    # 1: interface
-    # 2: ssid
-    # 3: key
-    [ `interface_exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
-    [ `interface_status $1` = "down" ] && echo "$1: Interface is DOWN." && return
+    [ `exists $1` = "no" ] && echo "$1: No such interface." >&2 && return
+    [ `getStatus $1` = "down" ] && echo "$1: Interface is DOWN." && return
     echo "$1: Connecting to \`$2'..."
     iwconfig $1 essid "$2" key "s:$3"
     echo "$1: Obtaining IP address from \`$2'..."
     dhclient $1
-    wlan_status $1
+    status_single $1
 }
 
 # Main program
@@ -247,115 +160,74 @@ function wlan_connect() {
 case "$1" in
     --help)
 	[ $# -gt 1 ] && echo "E: Unexpected argument: \`$2'" >&2 && exit
-	usage
-	;;
+	usage ;;
+    --version)
+	[ $# -gt 1 ] && echo "E: Unexpected argument: \`$2'" >&2 && exit
+	echo $(basename "$0")" v$VERSION ("$(uname -o)" "$(uname -r)")" ;;
     devices)
 	[ $# -gt 1 ] && echo "E: Unexpected argument: \`$2'" >&2 && exit
-	devices
-	;;
-    eth|wlan)
+	devices ;;
+    eth|wlan|usb)
 	case "$2" in
 	    list)
 		if [ $# -eq 2 ] ; then
-		    [ $1 = "eth" ] && eth_list || wlan_list
+		    type_list $1
 		else
+		    [ $# -gt 3 ] && echo "E: Unexpected argument: \`$4'" >&2 && exit
 		    case "$3" in
-			up)
-			    [ $# -gt 3 ] && echo "E: Unexpected argument: \`$4'" >&2 && exit
-			    [ $1 = "eth" ] && eth_list_up || wlan_list_up
-			    ;;
-			down)
-			    [ $# -gt 3 ] && echo "E: Unexpected argument: \`$4'" >&2 && exit
-			    [ $1 = "eth" ] && eth_list_down || wlan_list_down
-			    ;;
-			*)
-			    echo "E: Unrecognized argument: \`$3'" >&2 && exit 1
-			    ;;
+			up) type_list_up $1 ;;
+			down) type_list_down $1 ;;
+			*) echo "E: Unrecognized argument: \`$3'" >&2 && exit 1 ;;
 		    esac
 		fi
 		;;
 	    status)
 		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
-		[ $1 = "eth" ] && eth_status || wlan_status
-		;;
-	    *)
-		echo "E: Unrecognized argument: \`$2'" >&2 && exit 1
-		;;
-	esac
-	;;
+		type_status $1 ;;
+	    *) echo "E: Unrecognized argument: \`$2'" >&2 && exit 1 ;;
+	esac ;;
     list)
 	if [ $# -eq 1 ] ; then
-	    list
+	    interfaces_list
 	else
+	    [ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
 	    case "$2" in
-		up)
-		    [ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
-		    list_up
-		    ;;
-		down)
-		    [ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
-		    list_down
-		    ;;
-		*)
-		    echo "E: Unrecognized argument: \`$2'" >&2 && exit 1
-		    ;;
+		up) interfaces_list_up ;;
+		down) interfaces_list_down ;;
+		*) echo "E: Unrecognized argument: \`$2'" >&2 && exit 1 ;;
 	    esac
-	fi
-	;;
+	fi ;;
     status)
 	[ $# -gt 1 ] && echo "E: Unexpected argument: \`$2'" >&2 && exit
-	status
-	;;
-    eth[0-9])
+	interfaces_status ;;
+    eth[0-9]|usb[0])
+	[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
 	case "$2" in
-	    up)
-		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
-		eth_up "$1"
-		;;
-	    down)
-		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
-		eth_down "$1"
-		;;
-	    status)
-		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
-		eth_status "$1"
-		;;
-	    *)
-		echo "E: Unrecognized argument: \`$2'" >&2 && exit 1
-		;;
-	esac
-	;;
+	    up) interface_up "$1" ;;
+	    down) interface_down "$1" ;;
+	    status) interface_status "$1" ;;
+	    *) echo "E: Unrecognized argument: \`$2'" >&2 && exit 1 ;;
+	esac ;;
     wlan[0-9])
+	[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
 	case "$2" in
-	    up)
-		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
-		wlan_up "$1"
-		;;
+	    up) interface_up "$1" ;;
 	    down)
 		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
-		wlan_down "$1"
-		;;
+		interface_down "$1" ;;
 	    status)
 		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
-		wlan_status "$1"
-		;;
+		interface_status "$1" ;;
 	    ssid)
 		[ $# -gt 2 ] && echo "E: Unexpected argument: \`$3'" >&2 && exit
-		wlan_ssid "$1"
-		;;
+		wlan_ssid "$1" ;;
 	    connect)
 		[ $# -eq 2 ] && echo "E: Missing argument: <ssid>" >&2 && exit 1
 		[ $# -gt 4 ] && echo "E: Unexpected argument: \`$5'" >&2 && exit
-		wlan_connect "$1" "$2" "$3"
-		;;
-	    *)
-		echo "E: Unrecognized argument: \`$2'" >&2 && exit 1
-		;;
-	esac
-	;;
-    *)
-	echo "E: Unrecognized argument: \`$1'" >&2 && exit 1
-	;;
+		wlan_connect "$1" "$2" "$3" ;;
+	    *) echo "E: Unrecognized argument: \`$2'" >&2 && exit 1 ;;
+	esac ;;
+    *) echo "E: Unrecognized argument: \`$1'" >&2 && exit 1 ;;
 esac
 
 exit 0
diff --git a/root_only/ping-apt b/root_only/ping-apt
--- a/root_only/ping-apt
+++ b/root_only/ping-apt
@@ -12,21 +12,22 @@
 OK=$(echo -e "[ \033[0;32mok\033[0;0m ]")
 KO=$(echo -e "[ \033[0;31mko\033[0;0m ]")
 
-[ "_`which curl`" = "_" ] && echo "E: curl: Command not found" >&2 && exit 1
+[ -z "`which curl`" ] && echo "E: curl: Command not found" >&2 && exit 1
 
 function ping_apt() {
     HTTP_STATUS=$(curl -I "$URL" 2>/dev/null | grep -E '^HTTP' | tr -d "\r" | awk '{print "HTTP/"$2}')
-    if [ "$HTTP_STATUS" != "HTTP/200" ] ; then
-	LOCATION=$(curl -I "$URL" 2>/dev/null | grep -E '^Location' | tr -d "\r" | cut -d' ' -f2-)
-	if [ "_$LOCATION" != "_" ] ; then
-	    HTTP_STATUS=$(curl -I "$LOCATION" 2>/dev/null | grep -E '^HTTP' | tr -d "\r" | awk '{print "HTTP/"$2}')
-	    URL="$LOCATION"
-	fi
-    fi
-    if [ "$HTTP_STATUS" == "HTTP/200" ] ; then
+    [ -z "$HTTP_STATUS" ] && return
+    if [ "$HTTP_STATUS" = "HTTP/200" ] ; then
 	echo -ne "   $HTTP_STATUS $URL"
 	OFFSET=$(echo "`tput cols` - `echo $URL | wc -c` + 2" | bc -q)
 	printf "%${OFFSET}s\n" "$OK"
+    elif [ "$HTTP_STATUS" = "HTTP/302" ] ; then
+	LOCATION=$(curl -I "$URL" 2>/dev/null | grep -E '^Location' | tr -d "\r" | cut -d' ' -f2-)
+	if [ ! -z "$LOCATION" ] ; then
+	    HTTP_STATUS=$(curl -I "$LOCATION" 2>/dev/null | grep -E '^HTTP' | tr -d "\r" | awk '{print "HTTP/"$2}')
+	    #URL=$(echo $LOCATION | cut -d' ' -f3- | cut -d'/' -f1,2,3)
+	    ping_apt "$FILE" "$LINE" "$LOCATION"
+	fi
     else
 	echo -ne "   $HTTP_STATUS $URL ($FILE:$LINE)"
 	OFFSET=$(echo "`tput cols` - `echo "$URL$FILE$LINE" | wc -c` - 2" | bc -q)
@@ -54,7 +55,7 @@ else
 	    grep -HEn '^deb' $FILE 2>/dev/null | sed -e 's/:deb//g' -e 's/:/ /' | awk '{print $1" "$2" " $3}' | \
 		while read REPOSITORY ; do
 		    LINE=$(echo $REPOSITORY | cut -d' ' -f2)
-		    URL=$(echo $REPOSITORY | cut -d' ' -f3-)
+		    URL=$(echo $REPOSITORY | cut -d' ' -f3- | cut -d'/' -f1,2,3)
 		    ping_apt "$FILE" "$LINE" "$URL"
                 done
            done
diff --git a/root_only/power_off b/root_only/power_off
--- a/root_only/power_off
+++ b/root_only/power_off
@@ -9,7 +9,7 @@
 # under certain conditions.
 #
 
-[ "_`which shutdown`" = "_" ] && echo "E: shutdown: Command not found" >&2 && exit 1
+[ -z "`which shutdown`" ] && echo "E: shutdown: Command not found" >&2 && exit 1
 
 function usage() {
     echo "Usage: `basename $0` <TIME>" >&2
@@ -18,8 +18,7 @@ function usage() {
 }
 
 function down() {
-    # 1: time
-    shutdown -h "+$1" "System is going down NOW!" &
+    shutdown -h "+$1" &
 }
 
 function cancel() {
@@ -30,32 +29,32 @@ PID=$(ps aux | grep "shutdown -h" | grep -v "grep shutdown -h" | awk '{print $2}
 
 if [ $# -eq 0 ] ; then
     usage
-elif [ "_`echo "$1" | egrep '^[0-9]+:[0-9]+:[0-9]+$'`" != "_" ] ; then
+elif [ ! -z "`echo "$1" | egrep '^[0-9]+:[0-9]+:[0-9]+$'`" ] ; then
     # dd:hh:mm
     DAYS=$(echo "$1" | cut -d':' -f1)
     HOURS=$(echo "$1" | cut -d':' -f2)
     MINUTES=$(echo "$1" | cut -d':' -f3)
-    [ "_$PID" != "_" ] && cancel
+    [ ! -z "$PID" ] && cancel
     echo "Shutdown in: ${DAYS}d ${HOURS}h${MINUTES}m"
     down $(echo "$DAYS * 3600 + $HOURS * 60 + $MINUTES" | bc -q)
-elif [ "_`echo "$1" | egrep '^[0-9]+:[0-9]+$'`" != "_" ] ; then
+elif [ ! -z "`echo "$1" | egrep '^[0-9]+:[0-9]+$'`" ] ; then
     # hh:mm
     DAYS=0
     HOURS=$(echo "$1" | cut -d':' -f1)
     MINUTES=$(echo "$1" | cut -d':' -f2)
-    [ "_$PID" != "_" ] && cancel
+    [ ! -z "$PID" ] && cancel
     echo "Shutdown in: ${DAYS}d ${HOURS}h${MINUTES}m"
     down $(echo "$DAYS * 3600 + $HOURS * 60 + $MINUTES" | bc -q)
-elif [ "_`echo "$1" | egrep '^[0-9]+$'`" != "_" ] ; then
+elif [ ! -z "`echo "$1" | egrep '^[0-9]+$'`" ] ; then
     # mm
     DAYS=0
     HOURS=0
     MINUTES=$(echo "$1")
-    [ "_$PID" != "_" ] && cancel
+    [ ! -z "$PID" ] && cancel
     echo "Shutdown in: ${DAYS}d ${HOURS}h${MINUTES}m"
     down $(echo "$DAYS * 3600 + $HOURS * 60 + $MINUTES" | bc -q)
 elif [ "_$1" = "_cancel" ] ; then
-    if [ "_$PID" != "_" ] ; then
+    if [ ! -z "$PID" ] ; then
 	echo "Shutdown (pid:$PID) canceled."
 	cancel
     else
